
/* THIS FILE IS AUTO-GENERATED!  DO NOT EDIT!
**
** To modify this file, regenerate after editing
** any RKY file
*/

#if !defined KERNEL_NOTIFICATION_ID_FLAG 
#define KERNEL_NOTIFICATION_ID_FLAG                                    0x01000000
#define NEEDS_KERNEL_NOTIFICATION(id)                                  (id & KERNEL_NOTIFICATION_ID_FLAG)
#endif // KERNEL_NOTIFICATION_ID_FLAG 

#define DISPLAY_CLONE_GROUP_IDS_ID                0x5818a91d
#define DISPLAY_CLONE_GROUP_IDS_STRING_PLAIN      "DISPLAY_CLONE_GROUP_IDS"
#define DISPLAY_CLONE_GROUP_IDS_OVERINSTALL       1 // MERGE
#define DISPLAY_CLONE_GROUP_IDS_NONE                                   L""
#define DISPLAY_CLONE_GROUP_IDS_DEFAULT           DISPLAY_CLONE_GROUP_IDS_NONE
#define DISPLAY_CLONE_GROUP_IDS_APP_PROFILE_ENUM  EN_NONE


#define DISPLAY_COLS_ID                0x58e21bd4
#define DISPLAY_COLS_STRING_PLAIN      "DISPLAY_COLS"
#define DISPLAY_COLS_OVERINSTALL       1 // MERGE
#define DISPLAY_COLS_DEFAULT           DISPLAY_COLS_NAMESPACE::MIN
#define DISPLAY_COLS_APP_PROFILE_ENUM  EN_NONE
namespace DISPLAY_COLS_NAMESPACE
{
    enum DISPLAY_COLS_ENUM 
    {
        MIN = 1,
        MAX = 255
    };
}


#define DISPLAY_GRID_BRIGHTNESS_ID                0x5888f014
#define DISPLAY_GRID_BRIGHTNESS_STRING_PLAIN      "DISPLAY_GRID_BRIGHTNESS"
#define DISPLAY_GRID_BRIGHTNESS_OVERINSTALL       1 // MERGE
#define DISPLAY_GRID_BRIGHTNESS_DEFAULT           DISPLAY_GRID_BRIGHTNESS_NAMESPACE::NORMAL
#define DISPLAY_GRID_BRIGHTNESS_APP_PROFILE_ENUM  EN_NONE
namespace DISPLAY_GRID_BRIGHTNESS_NAMESPACE
{
    enum DISPLAY_GRID_BRIGHTNESS_ENUM 
    {
        MIN = 0x00000000,
        NORMAL = 0x42480000,
        MAX = 0x42C80000
    };
}


#define DISPLAY_GRID_CONTRAST_ID                0x5899d709
#define DISPLAY_GRID_CONTRAST_STRING_PLAIN      "DISPLAY_GRID_CONTRAST"
#define DISPLAY_GRID_CONTRAST_OVERINSTALL       1 // MERGE
#define DISPLAY_GRID_CONTRAST_DEFAULT           DISPLAY_GRID_CONTRAST_NAMESPACE::NORMAL
#define DISPLAY_GRID_CONTRAST_APP_PROFILE_ENUM  EN_NONE
namespace DISPLAY_GRID_CONTRAST_NAMESPACE
{
    enum DISPLAY_GRID_CONTRAST_ENUM 
    {
        MIN = 0x00000000,
        NORMAL = 0x42480000,
        MAX = 0x42C80000
    };
}


#define DISPLAY_GRID_CSC_ID                0x5822d5ee
#define DISPLAY_GRID_CSC_STRING_PLAIN      "DISPLAY_GRID_CSC"
#define DISPLAY_GRID_CSC_OVERINSTALL       1 // MERGE
#define DISPLAY_GRID_CSC_NONE                                          L""
#define DISPLAY_GRID_CSC_DEFAULT           DISPLAY_GRID_CSC_NONE
#define DISPLAY_GRID_CSC_APP_PROFILE_ENUM  EN_NONE


#define DISPLAY_GRID_GAMMA_ID                0x58f95c9b
#define DISPLAY_GRID_GAMMA_STRING_PLAIN      "DISPLAY_GRID_GAMMA"
#define DISPLAY_GRID_GAMMA_OVERINSTALL       1 // MERGE
#define DISPLAY_GRID_GAMMA_DEFAULT           DISPLAY_GRID_GAMMA_NAMESPACE::NORMAL
#define DISPLAY_GRID_GAMMA_APP_PROFILE_ENUM  EN_NONE
namespace DISPLAY_GRID_GAMMA_NAMESPACE
{
    enum DISPLAY_GRID_GAMMA_ENUM 
    {
        MIN = 0x3E99999A,
        NORMAL = 0x3f800000,
        MAX = 0x40333333
    };
}


#define DISPLAY_GRID_GAMMA_RAMP_ID                0x58d3388f
#define DISPLAY_GRID_GAMMA_RAMP_STRING_PLAIN      "DISPLAY_GRID_GAMMA_RAMP"
#define DISPLAY_GRID_GAMMA_RAMP_OVERINSTALL       1 // MERGE
#define DISPLAY_GRID_GAMMA_RAMP_NONE                                   L""
#define DISPLAY_GRID_GAMMA_RAMP_DEFAULT           DISPLAY_GRID_GAMMA_RAMP_NONE
#define DISPLAY_GRID_GAMMA_RAMP_APP_PROFILE_ENUM  EN_NONE


#define DISPLAY_GRID_POS_COL_ID                0x58ba728b
#define DISPLAY_GRID_POS_COL_STRING_PLAIN      "DISPLAY_GRID_POS_COL"
#define DISPLAY_GRID_POS_COL_OVERINSTALL       1 // MERGE
#define DISPLAY_GRID_POS_COL_DEFAULT           DISPLAY_GRID_POS_COL_NAMESPACE::MIN
#define DISPLAY_GRID_POS_COL_APP_PROFILE_ENUM  EN_NONE
namespace DISPLAY_GRID_POS_COL_NAMESPACE
{
    enum DISPLAY_GRID_POS_COL_ENUM 
    {
        MIN = 0,
        MAX = 100000
    };
}


#define DISPLAY_GRID_POS_ROW_ID                0x584b70fe
#define DISPLAY_GRID_POS_ROW_STRING_PLAIN      "DISPLAY_GRID_POS_ROW"
#define DISPLAY_GRID_POS_ROW_OVERINSTALL       1 // MERGE
#define DISPLAY_GRID_POS_ROW_DEFAULT           DISPLAY_GRID_POS_ROW_NAMESPACE::MIN
#define DISPLAY_GRID_POS_ROW_APP_PROFILE_ENUM  EN_NONE
namespace DISPLAY_GRID_POS_ROW_NAMESPACE
{
    enum DISPLAY_GRID_POS_ROW_ENUM 
    {
        MIN = 0,
        MAX = 100000
    };
}


#define DISPLAY_GRID_ROTATION_ID                0x589fe89a
#define DISPLAY_GRID_ROTATION_STRING_PLAIN      "DISPLAY_GRID_ROTATION"
#define DISPLAY_GRID_ROTATION_OVERINSTALL       1 // MERGE
#define DISPLAY_GRID_ROTATION_DEFAULT           DISPLAY_GRID_ROTATION_NAMESPACE::ROTATE_0
#define DISPLAY_GRID_ROTATION_APP_PROFILE_ENUM  EN_NONE
namespace DISPLAY_GRID_ROTATION_NAMESPACE
{
    enum DISPLAY_GRID_ROTATION_ENUM 
    {
        ROTATE_0 = 0,
        ROTATE_90 = 1,
        ROTATE_180 = 2,
        ROTATE_270 = 3,
        ROTATE_IGNORED = 4
    };
}


#define DISPLAY_GRID_SCALING_ID                0x58d4b0b4
#define DISPLAY_GRID_SCALING_STRING_PLAIN      "DISPLAY_GRID_SCALING"
#define DISPLAY_GRID_SCALING_OVERINSTALL       1 // MERGE
#define DISPLAY_GRID_SCALING_DEFAULT           DISPLAY_GRID_SCALING_NAMESPACE::SCALING_TO_ASPECT_SCANOUT_TO_NATIVE
#define DISPLAY_GRID_SCALING_APP_PROFILE_ENUM  EN_NONE
namespace DISPLAY_GRID_SCALING_NAMESPACE
{
    enum DISPLAY_GRID_SCALING_ENUM 
    {
        SCALING_TO_CLOSEST = 1,
        SCALING_MONITOR_SCALING = 1,
        SCALING_TO_NATIVE = 2,
        SCALING_ADAPTER_SCALING = 2,
        SCANOUT_TO_NATIVE = 3,
        SCALING_CENTERED = 3,
        SCALING_TO_ASPECT_SCANOUT_TO_NATIVE = 5,
        SCALING_ASPECT_SCALING = 5,
        SCALING_TO_ASPECT_SCANOUT_TO_CLOSEST = 6,
        SCANOUT_TO_CLOSEST = 7
    };
}


#define DISPLAY_IDS_ID                0x58b21e43
#define DISPLAY_IDS_STRING_PLAIN      "DISPLAY_IDS"
#define DISPLAY_IDS_OVERINSTALL       1 // MERGE
#define DISPLAY_IDS_NONE                                               L""
#define DISPLAY_IDS_DEFAULT           DISPLAY_IDS_NONE
#define DISPLAY_IDS_APP_PROFILE_ENUM  EN_NONE


#define DISPLAY_MODE_ID                0x58c7b07c
#define DISPLAY_MODE_STRING_PLAIN      "DISPLAY_MODE"
#define DISPLAY_MODE_OVERINSTALL       1 // MERGE
#define DISPLAY_MODE_NATIVE                                            L"native"
#define DISPLAY_MODE_DEFAULT           DISPLAY_MODE_NATIVE
#define DISPLAY_MODE_APP_PROFILE_ENUM  EN_NONE


#define DISPLAY_POS_COLS_ID                0x586748c2
#define DISPLAY_POS_COLS_STRING_PLAIN      "DISPLAY_POS_COLS"
#define DISPLAY_POS_COLS_OVERINSTALL       1 // MERGE
#define DISPLAY_POS_COLS_NONE                                          L"0"
#define DISPLAY_POS_COLS_DEFAULT           DISPLAY_POS_COLS_NONE
#define DISPLAY_POS_COLS_APP_PROFILE_ENUM  EN_NONE


#define DISPLAY_POS_ROWS_ID                0x5879ddc6
#define DISPLAY_POS_ROWS_STRING_PLAIN      "DISPLAY_POS_ROWS"
#define DISPLAY_POS_ROWS_OVERINSTALL       1 // MERGE
#define DISPLAY_POS_ROWS_NONE                                          L"0"
#define DISPLAY_POS_ROWS_DEFAULT           DISPLAY_POS_ROWS_NONE
#define DISPLAY_POS_ROWS_APP_PROFILE_ENUM  EN_NONE


#define DISPLAY_ROTATION_ID                0x58decfa8
#define DISPLAY_ROTATION_STRING_PLAIN      "DISPLAY_ROTATION"
#define DISPLAY_ROTATION_OVERINSTALL       1 // MERGE
#define DISPLAY_ROTATION_NONE                                          L"0"
#define DISPLAY_ROTATION_DEFAULT           DISPLAY_ROTATION_NONE
#define DISPLAY_ROTATION_APP_PROFILE_ENUM  EN_NONE


#define DISPLAY_ROWS_ID                0x5822918d
#define DISPLAY_ROWS_STRING_PLAIN      "DISPLAY_ROWS"
#define DISPLAY_ROWS_OVERINSTALL       1 // MERGE
#define DISPLAY_ROWS_DEFAULT           DISPLAY_ROWS_NAMESPACE::MIN
#define DISPLAY_ROWS_APP_PROFILE_ENUM  EN_NONE
namespace DISPLAY_ROWS_NAMESPACE
{
    enum DISPLAY_ROWS_ENUM 
    {
        MIN = 1,
        MAX = 255
    };
}


#define DISPLAY_SCALING_ID                0x587b0428
#define DISPLAY_SCALING_STRING_PLAIN      "DISPLAY_SCALING"
#define DISPLAY_SCALING_OVERINSTALL       1 // MERGE
#define DISPLAY_SCALING_NONE                                           L"0"
#define DISPLAY_SCALING_DEFAULT           DISPLAY_SCALING_NONE
#define DISPLAY_SCALING_APP_PROFILE_ENUM  EN_NONE


#define OVERLAP_COLS_ID                0x58eb619d
#define OVERLAP_COLS_STRING_PLAIN      "OVERLAP_COLS"
#define OVERLAP_COLS_OVERINSTALL       1 // MERGE
#define OVERLAP_COLS_NONE                                              L"0"
#define OVERLAP_COLS_DEFAULT           OVERLAP_COLS_NONE
#define OVERLAP_COLS_APP_PROFILE_ENUM  EN_NONE


#define OVERLAP_ROWS_ID                0x58dd36c1
#define OVERLAP_ROWS_STRING_PLAIN      "OVERLAP_ROWS"
#define OVERLAP_ROWS_OVERINSTALL       1 // MERGE
#define OVERLAP_ROWS_NONE                                              L"0"
#define OVERLAP_ROWS_DEFAULT           OVERLAP_ROWS_NONE
#define OVERLAP_ROWS_APP_PROFILE_ENUM  EN_NONE


