
/* THIS FILE IS AUTO-GENERATED!  DO NOT EDIT!
**
** To modify this file, regenerate after editing
** any RKY file
*/

#if !defined KERNEL_NOTIFICATION_ID_FLAG 
#define KERNEL_NOTIFICATION_ID_FLAG                                    0x01000000
#define NEEDS_KERNEL_NOTIFICATION(id)                                  (id & KERNEL_NOTIFICATION_ID_FLAG)
#endif // KERNEL_NOTIFICATION_ID_FLAG 

#define NVDRS_FEATURE_AA_PREFIX            "_"
#define NVDRS_FEATURE_AA_STRING            ""
#define NVDRS_FEATURE_AA_ID                0xa0100006
#define NVDRS_FEATURE_AA_STRING_PLAIN      "NVDRS_FEATURE_AA"
#define NVDRS_FEATURE_AA_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_AA_DEFAULT           NVDRS_FEATURE_AA_NAMESPACE::DEFAULT
#define NVDRS_FEATURE_AA_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_AA_NAMESPACE
{
    enum NVDRS_FEATURE_AA_ENUM 
    {
        NONE = 0x00000000,
        TREAT_OVERRIDE_AS_APP_CONTROLLED = 0x00000001,
        TREAT_OVERRIDE_AS_ENHANCE = 0x00000002,
        DISABLE_OVERRIDE = 0x00000003,
        TREAT_ENHANCE_AS_APP_CONTROLLED = 0x00000004,
        TREAT_ENHANCE_AS_OVERRIDE = 0x00000008,
        DISABLE_ENHANCE = 0x0000000c,
        MAP_VCAA_TO_MULTISAMPLING = 0x00010000,
        SLI_DISABLE_TRANSPARENCY_SUPERSAMPLING = 0x00020000,
        DISABLE_CPLAA = 0x00040000,
        SKIP_RT_DIM_CHECK_FOR_ENHANCE = 0x00080000,
        DISABLE_SLIAA = 0x00100000,
        DEFAULT = 0x00000000,
        AA_RT_BPP_DIV_4 = 0xf0000000,
        AA_RT_BPP_DIV_4_SHIFT = 28,
        NON_AA_RT_BPP_DIV_4 = 0x0f000000,
        NON_AA_RT_BPP_DIV_4_SHIFT = 24,
        MASK = 0xff1f000f
    };
}


#define NVDRS_FEATURE_AA_GAMMA_CORRECTION_PREFIX            "_"
#define NVDRS_FEATURE_AA_GAMMA_CORRECTION_STRING            ""
#define NVDRS_FEATURE_AA_GAMMA_CORRECTION_ID                0xa0100004
#define NVDRS_FEATURE_AA_GAMMA_CORRECTION_STRING_PLAIN      "NVDRS_FEATURE_AA_GAMMA_CORRECTION"
#define NVDRS_FEATURE_AA_GAMMA_CORRECTION_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_AA_GAMMA_CORRECTION_DEFAULT           NVDRS_FEATURE_AA_GAMMA_CORRECTION_NAMESPACE::DEFAULT        /*"Default"*/
#define NVDRS_FEATURE_AA_GAMMA_CORRECTION_DEFAULT_FERMI     NVDRS_FEATURE_AA_GAMMA_CORRECTION_NAMESPACE::DEFAULT_FERMI        /*"Default Fermi"*/
#define NVDRS_FEATURE_AA_GAMMA_CORRECTION_DEFAULT_TESLA     NVDRS_FEATURE_AA_GAMMA_CORRECTION_NAMESPACE::DEFAULT_TESLA        /*"Default Tesla"*/
#define NVDRS_FEATURE_AA_GAMMA_CORRECTION_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_AA_GAMMA_CORRECTION_NAMESPACE
{
    enum NVDRS_FEATURE_AA_GAMMA_CORRECTION_ENUM 
    {
        MASK = 0x00000003,
        OFF = 0x00000000,
        ON_IF_FOS = 0x00000001,
        ON_ALWAYS = 0x00000002,
        MAX = 0x00000004,
        DEFAULT = 0x00000005,
        DEFAULT_TESLA = 0x00000006,
        DEFAULT_FERMI = 0x00000007
    };
}


#define NVDRS_FEATURE_AA_MODE_SELECTOR_PREFIX            "_"
#define NVDRS_FEATURE_AA_MODE_SELECTOR_STRING            ""
#define NVDRS_FEATURE_AA_MODE_SELECTOR_ID                0xa0100005
#define NVDRS_FEATURE_AA_MODE_SELECTOR_STRING_PLAIN      "NVDRS_FEATURE_AA_MODE_SELECTOR"
#define NVDRS_FEATURE_AA_MODE_SELECTOR_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_AA_MODE_SELECTOR_DEFAULT           NVDRS_FEATURE_AA_MODE_SELECTOR_NAMESPACE::APP_CONTROL
#define NVDRS_FEATURE_AA_MODE_SELECTOR_DEFAULT_FERMI     NVDRS_FEATURE_AA_MODE_SELECTOR_NAMESPACE::APP_CONTROL
#define NVDRS_FEATURE_AA_MODE_SELECTOR_DEFAULT_TESLA     NVDRS_FEATURE_AA_MODE_SELECTOR_NAMESPACE::APP_CONTROL
#define NVDRS_FEATURE_AA_MODE_SELECTOR_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_AA_MODE_SELECTOR_NAMESPACE
{
    enum NVDRS_FEATURE_AA_MODE_SELECTOR_ENUM 
    {
        MASK = 0x00000003,
        APP_CONTROL = 0x00000000,
        OVERRIDE = 0x00000001,
        ENHANCE = 0x00000002,
        MAX = 0x00000004
    };
}


#define NVDRS_FEATURE_AA_REPLAY_TRANSPARENCY_PREFIX            "_"
#define NVDRS_FEATURE_AA_REPLAY_TRANSPARENCY_STRING            ""
#define NVDRS_FEATURE_AA_REPLAY_TRANSPARENCY_ID                0xa0100007
#define NVDRS_FEATURE_AA_REPLAY_TRANSPARENCY_STRING_PLAIN      "NVDRS_FEATURE_AA_REPLAY_TRANSPARENCY"
#define NVDRS_FEATURE_AA_REPLAY_TRANSPARENCY_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_AA_REPLAY_TRANSPARENCY_DEFAULT           0x00000000        /*"TRANSPARENCY_DEFAULT"*/
#define NVDRS_FEATURE_AA_REPLAY_TRANSPARENCY_DEFAULT_FERMI     0x00000000        /*"TRANSPARENCY_DEFAULT_FERMI"*/
#define NVDRS_FEATURE_AA_REPLAY_TRANSPARENCY_DEFAULT_TESLA     0x00000000        /*"TRANSPARENCY_DEFAULT_TESLA"*/
#define NVDRS_FEATURE_AA_REPLAY_TRANSPARENCY_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_AA_REPLAY_TRANSPARENCY_NAMESPACE
{
    enum NVDRS_FEATURE_AA_REPLAY_TRANSPARENCY_ENUM 
    {
        SAMPLES_MASK = 0x00000070,
        SAMPLES_ONE = 0x00000000,
        SAMPLES_TWO = 0x00000010,
        SAMPLES_FOUR = 0x00000020,
        SAMPLES_EIGHT = 0x00000030,
        SAMPLES_MAX = 0x00000030,
        MODE_MASK = 0x0000000f,
        MODE_OFF = 0x00000000,
        MODE_ALPHA_TEST = 0x00000001,
        MODE_PIXEL_KILL = 0x00000002,
        MODE_DYN_BRANCH = 0x00000004,
        MODE_OPTIMAL = 0x00000004,
        MODE_ALL = 0x00000008,
        MODE_MAX = 0x0000000f,
        TRANSPARENCY = 0x00000023,
        DISALLOW_TRAA = 0x00000100,
        TRANSPARENCY_DEFAULT = 0x00000000,
        TRANSPARENCY_DEFAULT_TESLA = 0x00000000,
        TRANSPARENCY_DEFAULT_FERMI = 0x00000000,
        MASK = 0x0000017f
    };
}


#define NVDRS_FEATURE_ACE_POWERMODE_CPU_FREQUENCY_PREFIX            "_"
#define NVDRS_FEATURE_ACE_POWERMODE_CPU_FREQUENCY_STRING            ""
#define NVDRS_FEATURE_ACE_POWERMODE_CPU_FREQUENCY_ID                0xa02fa782
#define NVDRS_FEATURE_ACE_POWERMODE_CPU_FREQUENCY_STRING_PLAIN      "NVDRS_FEATURE_ACE_POWERMODE_CPU_FREQUENCY"
#define NVDRS_FEATURE_ACE_POWERMODE_CPU_FREQUENCY_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_ACE_POWERMODE_CPU_FREQUENCY_DEFAULT           NVDRS_FEATURE_ACE_POWERMODE_CPU_FREQUENCY_NAMESPACE::DEFAULT
#define NVDRS_FEATURE_ACE_POWERMODE_CPU_FREQUENCY_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_ACE_POWERMODE_CPU_FREQUENCY_NAMESPACE
{
    enum NVDRS_FEATURE_ACE_POWERMODE_CPU_FREQUENCY_ENUM 
    {
        NO_OVERRIDE = 0xffffffff,
        DEFAULT = 0x00000000
    };
}


#define NVDRS_FEATURE_ANISO_PREFIX            "_"
#define NVDRS_FEATURE_ANISO_STRING            ""
#define NVDRS_FEATURE_ANISO_ID                0xa0100002
#define NVDRS_FEATURE_ANISO_STRING_PLAIN      "NVDRS_FEATURE_ANISO"
#define NVDRS_FEATURE_ANISO_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_ANISO_DEFAULT           NVDRS_FEATURE_ANISO_NAMESPACE::DEFAULT
#define NVDRS_FEATURE_ANISO_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_ANISO_NAMESPACE
{
    enum NVDRS_FEATURE_ANISO_ENUM 
    {
        APP_CONTROL = 0x00100000,
        OFF = 1,
        _2X = 2,
        _4X = 4,
        _8X = 8,
        _16X = 16,
        MASK = 0x0000ffff,
        MAX = 0x00000010,
        DEFAULT = 1
    };
}


#define NVDRS_FEATURE_ANISO_OPTS_PREFIX            "_"
#define NVDRS_FEATURE_ANISO_OPTS_STRING            ""
#define NVDRS_FEATURE_ANISO_OPTS_ID                0xa010001a
#define NVDRS_FEATURE_ANISO_OPTS_STRING_PLAIN      "NVDRS_FEATURE_ANISO_OPTS"
#define NVDRS_FEATURE_ANISO_OPTS_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_ANISO_OPTS_DEFAULT           NVDRS_FEATURE_ANISO_OPTS_NAMESPACE::OFF
#define NVDRS_FEATURE_ANISO_OPTS_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_ANISO_OPTS_NAMESPACE
{
    enum NVDRS_FEATURE_ANISO_OPTS_ENUM 
    {
        OFF = 0x00000000,
        _0 = 0x00000000,
        DISABLED = 0x00000000,
        ON = 0x00000001,
        _1 = 0x00000001,
        ENABLED = 0x00000001
    };
}


#define NVDRS_FEATURE_ANISO_SAMPLE_OPS_PREFIX            "_"
#define NVDRS_FEATURE_ANISO_SAMPLE_OPS_STRING            ""
#define NVDRS_FEATURE_ANISO_SAMPLE_OPS_ID                0xa0100016
#define NVDRS_FEATURE_ANISO_SAMPLE_OPS_STRING_PLAIN      "NVDRS_FEATURE_ANISO_SAMPLE_OPS"
#define NVDRS_FEATURE_ANISO_SAMPLE_OPS_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_ANISO_SAMPLE_OPS_DEFAULT           NVDRS_FEATURE_ANISO_SAMPLE_OPS_NAMESPACE::OFF
#define NVDRS_FEATURE_ANISO_SAMPLE_OPS_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_ANISO_SAMPLE_OPS_NAMESPACE
{
    enum NVDRS_FEATURE_ANISO_SAMPLE_OPS_ENUM 
    {
        OFF = 0x00000000,
        DISABLED = 0x00000000,
        ON = 0x00000001,
        ENABLED = 0x00000001
    };
}


#define NVDRS_FEATURE_AO_MODE_PREFIX            "_"
#define NVDRS_FEATURE_AO_MODE_STRING            ""
#define NVDRS_FEATURE_AO_MODE_ID                0xa0100001
#define NVDRS_FEATURE_AO_MODE_STRING_PLAIN      "NVDRS_FEATURE_AO_MODE"
#define NVDRS_FEATURE_AO_MODE_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_AO_MODE_DEFAULT           NVDRS_FEATURE_AO_MODE_NAMESPACE::OFF
#define NVDRS_FEATURE_AO_MODE_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_AO_MODE_NAMESPACE
{
    enum NVDRS_FEATURE_AO_MODE_ENUM 
    {
        OFF = 0,
        LOW = 1,
        MEDIUM = 2,
        HIGH = 3,
        NOT_SUPPORTED = -1
    };
}


#define NVDRS_FEATURE_BATTERY_BOOST_PREFIX            "_"
#define NVDRS_FEATURE_BATTERY_BOOST_STRING            ""
#define NVDRS_FEATURE_BATTERY_BOOST_ID                0xa0100020
#define NVDRS_FEATURE_BATTERY_BOOST_STRING_PLAIN      "NVDRS_FEATURE_BATTERY_BOOST"
#define NVDRS_FEATURE_BATTERY_BOOST_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_BATTERY_BOOST_DEFAULT           NVDRS_FEATURE_BATTERY_BOOST_NAMESPACE::OPTIMAL
#define NVDRS_FEATURE_BATTERY_BOOST_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_BATTERY_BOOST_NAMESPACE
{
    enum NVDRS_FEATURE_BATTERY_BOOST_ENUM 
    {
        MIN = 0x00000001,
        MAX = 0x000000ff,
        ENABLED = 0x10000000,
        OPTIMAL = 0x0000001e
    };
}


#define NVDRS_FEATURE_BUFFER_FLIP_MODE_PREFIX            "_"
#define NVDRS_FEATURE_BUFFER_FLIP_MODE_STRING            ""
#define NVDRS_FEATURE_BUFFER_FLIP_MODE_ID                0xa0100008
#define NVDRS_FEATURE_BUFFER_FLIP_MODE_STRING_PLAIN      "NVDRS_FEATURE_BUFFER_FLIP_MODE"
#define NVDRS_FEATURE_BUFFER_FLIP_MODE_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_BUFFER_FLIP_MODE_DEFAULT           NVDRS_FEATURE_BUFFER_FLIP_MODE_NAMESPACE::OFF
#define NVDRS_FEATURE_BUFFER_FLIP_MODE_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_BUFFER_FLIP_MODE_NAMESPACE
{
    enum NVDRS_FEATURE_BUFFER_FLIP_MODE_ENUM 
    {
        ON = 1,
        OFF = 0
    };
}


#define NVDRS_FEATURE_CUDA_EXCLUDED_GPUS_PREFIX            "_"
#define NVDRS_FEATURE_CUDA_EXCLUDED_GPUS_STRING            ""
#define NVDRS_FEATURE_CUDA_EXCLUDED_GPUS_ID                0xa0100009
#define NVDRS_FEATURE_CUDA_EXCLUDED_GPUS_STRING_PLAIN      "NVDRS_FEATURE_CUDA_EXCLUDED_GPUS"
#define NVDRS_FEATURE_CUDA_EXCLUDED_GPUS_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_CUDA_EXCLUDED_GPUS_NONE                          L"none"
#define NVDRS_FEATURE_CUDA_EXCLUDED_GPUS_DEFAULT           NVDRS_FEATURE_CUDA_EXCLUDED_GPUS_NONE
#define NVDRS_FEATURE_CUDA_EXCLUDED_GPUS_APP_PROFILE_ENUM  EN_NONE


#define NVDRS_FEATURE_DISPLAY_STEREO_MODE_PREFIX            "_"
#define NVDRS_FEATURE_DISPLAY_STEREO_MODE_STRING            ""
#define NVDRS_FEATURE_DISPLAY_STEREO_MODE_ID                0xa0100013
#define NVDRS_FEATURE_DISPLAY_STEREO_MODE_STRING_PLAIN      "NVDRS_FEATURE_DISPLAY_STEREO_MODE"
#define NVDRS_FEATURE_DISPLAY_STEREO_MODE_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_DISPLAY_STEREO_MODE_DEFAULT           NVDRS_FEATURE_DISPLAY_STEREO_MODE_NAMESPACE::SHUTTER_GLASSES
#define NVDRS_FEATURE_DISPLAY_STEREO_MODE_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_DISPLAY_STEREO_MODE_NAMESPACE
{
    enum NVDRS_FEATURE_DISPLAY_STEREO_MODE_ENUM 
    {
        SHUTTER_GLASSES = 0,
        VERTICAL_INTERLACED = 1,
        TWINVIEW = 2,
        NV17_SHUTTER_GLASSES_AUTO = 3,
        NV17_SHUTTER_GLASSES_DAC0 = 4,
        NV17_SHUTTER_GLASSES_DAC1 = 5,
        COLOR_LINE = 6,
        COLOR_INTERLEAVED = 7,
        ANAGLYPH = 8,
        HORIZONTAL_INTERLACED = 9,
        SIDE_FIELD = 10,
        SUB_FIELD = 11,
        CHECKERBOARD = 12,
        INVERSE_CHECKERBOARD = 13,
        TRIDELITY_SL = 14,
        TRIDELITY_MV = 15,
        SEEFRONT = 16,
        STEREO_MIRROR = 17,
        FRAME_SEQUENTIAL = 18,
        AUTODETECT_PASSIVE_MODE = 19,
        AEGIS_DT_FRAME_SEQUENTIAL = 20,
        OEM_EMITTER_FRAME_SEQUENTIAL = 21,
        USE_HW_DEFAULT = 0xffffffff,
        DEFAULT_GL = 3
    };
}


#define NVDRS_FEATURE_FXAA_PREFIX            "_"
#define NVDRS_FEATURE_FXAA_STRING            ""
#define NVDRS_FEATURE_FXAA_ID                0xa0100003
#define NVDRS_FEATURE_FXAA_STRING_PLAIN      "NVDRS_FEATURE_FXAA"
#define NVDRS_FEATURE_FXAA_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_FXAA_DEFAULT           NVDRS_FEATURE_FXAA_NAMESPACE::OFF
#define NVDRS_FEATURE_FXAA_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_FXAA_NAMESPACE
{
    enum NVDRS_FEATURE_FXAA_ENUM 
    {
        OFF = 0,
        DISABLED = 0,
        ON = 1,
        ENABLED = 1
    };
}


#define NVDRS_FEATURE_GAMESTREAM_FRAMECAP_PREFIX            "_"
#define NVDRS_FEATURE_GAMESTREAM_FRAMECAP_STRING            ""
#define NVDRS_FEATURE_GAMESTREAM_FRAMECAP_ID                0xa0100021
#define NVDRS_FEATURE_GAMESTREAM_FRAMECAP_STRING_PLAIN      "NVDRS_FEATURE_GAMESTREAM_FRAMECAP"
#define NVDRS_FEATURE_GAMESTREAM_FRAMECAP_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_GAMESTREAM_FRAMECAP_DEFAULT           NVDRS_FEATURE_GAMESTREAM_FRAMECAP_NAMESPACE::DISABLED
#define NVDRS_FEATURE_GAMESTREAM_FRAMECAP_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_GAMESTREAM_FRAMECAP_NAMESPACE
{
    enum NVDRS_FEATURE_GAMESTREAM_FRAMECAP_ENUM 
    {
        DISABLED = 0x00000000,
        FPS_20 = 0x00000014,
        FPS_30 = 0x0000001e,
        FPS_40 = 0x00000028,
        FPSMASK = 0x000000ff,
        FRL2 = 0x00010000,
        LOWER_FPS_TO_ALIGN = 0x00020000,
        FORCE_VSYNC_OFF = 0x00040000,
        GPS_WEB = 0x00080000,
        DISALLOWED = 0x00200000,
        USE_CPU_WAIT = 0x00400000,
        NO_LAG_OFFSET = 0x00800000,
        ACCURATE = 0x10000000,
        ALLOW_WINDOWED = 0x20000000,
        FORCEON = 0x40000000,
        ENABLED = 0x80000000,
        OPENGL_REMOTE_DESKTOP = 0xe000003c,
        MASK = 0xf0ef00ff
    };
}


#define NVDRS_FEATURE_HW_ACCEL_MULTIMON_PREFIX            "_"
#define NVDRS_FEATURE_HW_ACCEL_MULTIMON_STRING            ""
#define NVDRS_FEATURE_HW_ACCEL_MULTIMON_ID                0xa010000e
#define NVDRS_FEATURE_HW_ACCEL_MULTIMON_STRING_PLAIN      "NVDRS_FEATURE_HW_ACCEL_MULTIMON"
#define NVDRS_FEATURE_HW_ACCEL_MULTIMON_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_HW_ACCEL_MULTIMON_DEFAULT           NVDRS_FEATURE_HW_ACCEL_MULTIMON_NAMESPACE::PERFORMANCE_LCD
#define NVDRS_FEATURE_HW_ACCEL_MULTIMON_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_HW_ACCEL_MULTIMON_NAMESPACE
{
    enum NVDRS_FEATURE_HW_ACCEL_MULTIMON_ENUM 
    {
        SINGLE_MONITOR = 0,
        COMPATIBILITY_LCD = 1,
        COMPATIBILITY_GCD = 2,
        PERFORMANCE_LCD = 3,
        PERFORMANCE_GCD = 4,
        EXTENDED_SINGLE_MONITOR = 5,
        PERFORMANCE_QUADRO = 6,
        MULTIMON_BUFFER = 7
    };
}


#define NVDRS_FEATURE_MFAA_INTERLEAVED_PREFIX            "_"
#define NVDRS_FEATURE_MFAA_INTERLEAVED_STRING            ""
#define NVDRS_FEATURE_MFAA_INTERLEAVED_ID                0xa010000d
#define NVDRS_FEATURE_MFAA_INTERLEAVED_STRING_PLAIN      "NVDRS_FEATURE_MFAA_INTERLEAVED"
#define NVDRS_FEATURE_MFAA_INTERLEAVED_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_MFAA_INTERLEAVED_DEFAULT           NVDRS_FEATURE_MFAA_INTERLEAVED_NAMESPACE::OFF
#define NVDRS_FEATURE_MFAA_INTERLEAVED_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_MFAA_INTERLEAVED_NAMESPACE
{
    enum NVDRS_FEATURE_MFAA_INTERLEAVED_ENUM 
    {
        UNKNOWN = 0,
        OFF = 1,
        DISABLED = 1,
        ON = 2,
        ENABLED = 2
    };
}


#define NVDRS_FEATURE_NEG_LOD_BIAS_PREFIX            "_"
#define NVDRS_FEATURE_NEG_LOD_BIAS_STRING            ""
#define NVDRS_FEATURE_NEG_LOD_BIAS_ID                0xa0100017
#define NVDRS_FEATURE_NEG_LOD_BIAS_STRING_PLAIN      "NVDRS_FEATURE_NEG_LOD_BIAS"
#define NVDRS_FEATURE_NEG_LOD_BIAS_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_NEG_LOD_BIAS_DEFAULT           NVDRS_FEATURE_NEG_LOD_BIAS_NAMESPACE::OFF
#define NVDRS_FEATURE_NEG_LOD_BIAS_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_NEG_LOD_BIAS_NAMESPACE
{
    enum NVDRS_FEATURE_NEG_LOD_BIAS_ENUM 
    {
        OFF = 0x00000000,
        DISABLED = 0x00000000,
        ON = 0x00000001,
        ENABLED = 0x00000001
    };
}


#define NVDRS_FEATURE_OPTIMAL_REFRESHRATE_PREFIX            "_"
#define NVDRS_FEATURE_OPTIMAL_REFRESHRATE_STRING            ""
#define NVDRS_FEATURE_OPTIMAL_REFRESHRATE_ID                0xa010001f
#define NVDRS_FEATURE_OPTIMAL_REFRESHRATE_STRING_PLAIN      "NVDRS_FEATURE_OPTIMAL_REFRESHRATE"
#define NVDRS_FEATURE_OPTIMAL_REFRESHRATE_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_OPTIMAL_REFRESHRATE_DEFAULT           NVDRS_FEATURE_OPTIMAL_REFRESHRATE_NAMESPACE::MIN
#define NVDRS_FEATURE_OPTIMAL_REFRESHRATE_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_OPTIMAL_REFRESHRATE_NAMESPACE
{
    enum NVDRS_FEATURE_OPTIMAL_REFRESHRATE_ENUM 
    {
        MIN = 0x00000000,
        MAX = 0x000000ff
    };
}


#define NVDRS_FEATURE_OVERLAY_PIXEL_TYPE_PREFIX            "_"
#define NVDRS_FEATURE_OVERLAY_PIXEL_TYPE_STRING            ""
#define NVDRS_FEATURE_OVERLAY_PIXEL_TYPE_ID                0xa010000b
#define NVDRS_FEATURE_OVERLAY_PIXEL_TYPE_STRING_PLAIN      "NVDRS_FEATURE_OVERLAY_PIXEL_TYPE"
#define NVDRS_FEATURE_OVERLAY_PIXEL_TYPE_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_OVERLAY_PIXEL_TYPE_DEFAULT           NVDRS_FEATURE_OVERLAY_PIXEL_TYPE_NAMESPACE::CI
#define NVDRS_FEATURE_OVERLAY_PIXEL_TYPE_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_OVERLAY_PIXEL_TYPE_NAMESPACE
{
    enum NVDRS_FEATURE_OVERLAY_PIXEL_TYPE_ENUM 
    {
        NONE = 0x0,
        CI = 0x1,
        RGBA = 0x2,
        CI_AND_RGBA = 0x3
    };
}


#define NVDRS_FEATURE_OVERLAY_SUPPORT_PREFIX            "_"
#define NVDRS_FEATURE_OVERLAY_SUPPORT_STRING            ""
#define NVDRS_FEATURE_OVERLAY_SUPPORT_ID                0xa010000a
#define NVDRS_FEATURE_OVERLAY_SUPPORT_STRING_PLAIN      "NVDRS_FEATURE_OVERLAY_SUPPORT"
#define NVDRS_FEATURE_OVERLAY_SUPPORT_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_OVERLAY_SUPPORT_DEFAULT           NVDRS_FEATURE_OVERLAY_SUPPORT_NAMESPACE::OFF
#define NVDRS_FEATURE_OVERLAY_SUPPORT_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_OVERLAY_SUPPORT_NAMESPACE
{
    enum NVDRS_FEATURE_OVERLAY_SUPPORT_ENUM 
    {
        OFF = 0,
        ON = 1,
        FORCE_SW = 2
    };
}


#define NVDRS_FEATURE_POWER_MGMT_MODE_PREFIX            "_"
#define NVDRS_FEATURE_POWER_MGMT_MODE_STRING            ""
#define NVDRS_FEATURE_POWER_MGMT_MODE_ID                0xa0100011
#define NVDRS_FEATURE_POWER_MGMT_MODE_STRING_PLAIN      "NVDRS_FEATURE_POWER_MGMT_MODE"
#define NVDRS_FEATURE_POWER_MGMT_MODE_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_POWER_MGMT_MODE_DEFAULT           NVDRS_FEATURE_POWER_MGMT_MODE_NAMESPACE::ADAPTIVE
#define NVDRS_FEATURE_POWER_MGMT_MODE_DEFAULT_GL        NVDRS_FEATURE_POWER_MGMT_MODE_NAMESPACE::DRIVER_CONTROLLED
#define NVDRS_FEATURE_POWER_MGMT_MODE_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_POWER_MGMT_MODE_NAMESPACE
{
    enum NVDRS_FEATURE_POWER_MGMT_MODE_ENUM 
    {
        ADAPTIVE = 0x00000000,
        PREFER_MAX = 0x00000001,
        DRIVER_CONTROLLED = 0x00000002,
        PREFER_CONSISTENT_PERFORMANCE = 0x00000003,
        PREFER_MIN = 0x00000004,
        MIN = 0x00000000,
        MAX = 0x00000004
    };
}


#define NVDRS_FEATURE_PREFERRED_OGL_GPU_PREFIX            "_"
#define NVDRS_FEATURE_PREFERRED_OGL_GPU_STRING            ""
#define NVDRS_FEATURE_PREFERRED_OGL_GPU_ID                0xa010000f
#define NVDRS_FEATURE_PREFERRED_OGL_GPU_STRING_PLAIN      "NVDRS_FEATURE_PREFERRED_OGL_GPU"
#define NVDRS_FEATURE_PREFERRED_OGL_GPU_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_PREFERRED_OGL_GPU_AUTOSELECT                     L"autoselect"
#define NVDRS_FEATURE_PREFERRED_OGL_GPU_DEFAULT           NVDRS_FEATURE_PREFERRED_OGL_GPU_AUTOSELECT
#define NVDRS_FEATURE_PREFERRED_OGL_GPU_APP_PROFILE_ENUM  EN_NONE


#define NVDRS_FEATURE_PRERENDER_LIMIT_PREFIX            "_"
#define NVDRS_FEATURE_PRERENDER_LIMIT_STRING            ""
#define NVDRS_FEATURE_PRERENDER_LIMIT_ID                0xa010000c
#define NVDRS_FEATURE_PRERENDER_LIMIT_STRING_PLAIN      "NVDRS_FEATURE_PRERENDER_LIMIT"
#define NVDRS_FEATURE_PRERENDER_LIMIT_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_PRERENDER_LIMIT_DEFAULT           NVDRS_FEATURE_PRERENDER_LIMIT_NAMESPACE::APP_CONTROLLED
#define NVDRS_FEATURE_PRERENDER_LIMIT_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_PRERENDER_LIMIT_NAMESPACE
{
    enum NVDRS_FEATURE_PRERENDER_LIMIT_ENUM 
    {
        MIN = 0x00,
        MAX = 0xff,
        APP_CONTROLLED = 0x00,
        NONE = 0,
        ONE = 1,
        TWO = 2,
        THREE = 3,
        FOUR = 4,
        FIVE = 5,
        SIX = 6,
        SEVEN = 7,
        EIGHT = 8
    };
}


#define NVDRS_FEATURE_QUALITY_ENHANCEMENTS_PREFIX            "_"
#define NVDRS_FEATURE_QUALITY_ENHANCEMENTS_STRING            ""
#define NVDRS_FEATURE_QUALITY_ENHANCEMENTS_ID                0xa0100018
#define NVDRS_FEATURE_QUALITY_ENHANCEMENTS_STRING_PLAIN      "NVDRS_FEATURE_QUALITY_ENHANCEMENTS"
#define NVDRS_FEATURE_QUALITY_ENHANCEMENTS_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_QUALITY_ENHANCEMENTS_DEFAULT           NVDRS_FEATURE_QUALITY_ENHANCEMENTS_NAMESPACE::QUALITY
#define NVDRS_FEATURE_QUALITY_ENHANCEMENTS_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_QUALITY_ENHANCEMENTS_NAMESPACE
{
    enum NVDRS_FEATURE_QUALITY_ENHANCEMENTS_ENUM 
    {
        HIGHQUALITY = 0xfffffff6,
        HQ = 0xfffffff6,
        QUALITY = 0x00000000,
        Q = 0x00000000,
        _0 = 0x00000000,
        PERFORMANCE = 0x0000000a,
        P = 0x0000000a,
        a = 0x0000000a,
        _0xa = 0x0000000a,
        HIGHPERFORMANCE = 0x00000014,
        HP = 0x00000014,
        _14 = 0x00000014,
        _0x14 = 0x00000014
    };
}


#define NVDRS_FEATURE_QUIET_MODE_PREFIX            "_"
#define NVDRS_FEATURE_QUIET_MODE_STRING            ""
#define NVDRS_FEATURE_QUIET_MODE_ID                0xa0100022
#define NVDRS_FEATURE_QUIET_MODE_STRING_PLAIN      "NVDRS_FEATURE_QUIET_MODE"
#define NVDRS_FEATURE_QUIET_MODE_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_QUIET_MODE_DEFAULT           NVDRS_FEATURE_QUIET_MODE_NAMESPACE::DISABLED
#define NVDRS_FEATURE_QUIET_MODE_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_QUIET_MODE_NAMESPACE
{
    enum NVDRS_FEATURE_QUIET_MODE_ENUM 
    {
        MIN = 0x00000001,
        MAX = 0x000000ff,
        OPTIMAL = 0x0000003c,
        ENABLED = 0x10000000,
        DISABLED = 0x00000000
    };
}


#define NVDRS_FEATURE_SHADER_DISK_CACHE_PREFIX            "_"
#define NVDRS_FEATURE_SHADER_DISK_CACHE_STRING            ""
#define NVDRS_FEATURE_SHADER_DISK_CACHE_ID                0xa0100012
#define NVDRS_FEATURE_SHADER_DISK_CACHE_STRING_PLAIN      "NVDRS_FEATURE_SHADER_DISK_CACHE"
#define NVDRS_FEATURE_SHADER_DISK_CACHE_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_SHADER_DISK_CACHE_DEFAULT           0x1
#define NVDRS_FEATURE_SHADER_DISK_CACHE_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_SHADER_DISK_CACHE_NAMESPACE
{
    enum NVDRS_FEATURE_SHADER_DISK_CACHE_ENUM 
    {
        OFF = 0x00000000,
        DISABLED = 0x00000000,
        ON = 0x00000001,
        ENABLED = 0x00000001
    };
}


#define NVDRS_FEATURE_STEREO_EYES_SWAP_PREFIX            "_"
#define NVDRS_FEATURE_STEREO_EYES_SWAP_STRING            ""
#define NVDRS_FEATURE_STEREO_EYES_SWAP_ID                0xa0100015
#define NVDRS_FEATURE_STEREO_EYES_SWAP_STRING_PLAIN      "NVDRS_FEATURE_STEREO_EYES_SWAP"
#define NVDRS_FEATURE_STEREO_EYES_SWAP_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_STEREO_EYES_SWAP_DEFAULT           NVDRS_FEATURE_STEREO_EYES_SWAP_NAMESPACE::OFF
#define NVDRS_FEATURE_STEREO_EYES_SWAP_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_STEREO_EYES_SWAP_NAMESPACE
{
    enum NVDRS_FEATURE_STEREO_EYES_SWAP_ENUM 
    {
        OFF = 0,
        ON = 1
    };
}


#define NVDRS_FEATURE_STEREO_SUPPORT_PREFIX            "_"
#define NVDRS_FEATURE_STEREO_SUPPORT_STRING            ""
#define NVDRS_FEATURE_STEREO_SUPPORT_ID                0xa0100014
#define NVDRS_FEATURE_STEREO_SUPPORT_STRING_PLAIN      "NVDRS_FEATURE_STEREO_SUPPORT"
#define NVDRS_FEATURE_STEREO_SUPPORT_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_STEREO_SUPPORT_DEFAULT           NVDRS_FEATURE_STEREO_SUPPORT_NAMESPACE::OFF
#define NVDRS_FEATURE_STEREO_SUPPORT_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_STEREO_SUPPORT_NAMESPACE
{
    enum NVDRS_FEATURE_STEREO_SUPPORT_ENUM 
    {
        OFF = 0,
        ON = 1
    };
}


#define NVDRS_FEATURE_THREAD_CONTROL_PREFIX            "_"
#define NVDRS_FEATURE_THREAD_CONTROL_STRING            ""
#define NVDRS_FEATURE_THREAD_CONTROL_ID                0xa010001b
#define NVDRS_FEATURE_THREAD_CONTROL_STRING_PLAIN      "NVDRS_FEATURE_THREAD_CONTROL"
#define NVDRS_FEATURE_THREAD_CONTROL_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_THREAD_CONTROL_DEFAULT           0
#define NVDRS_FEATURE_THREAD_CONTROL_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_THREAD_CONTROL_NAMESPACE
{
    enum NVDRS_FEATURE_THREAD_CONTROL_ENUM 
    {
        ENABLE = 0x00000001,
        DISABLE = 0x00000002
    };
}


#define NVDRS_FEATURE_TRILINEAR_OPTS_PREFIX            "_"
#define NVDRS_FEATURE_TRILINEAR_OPTS_STRING            ""
#define NVDRS_FEATURE_TRILINEAR_OPTS_ID                0xa0100019
#define NVDRS_FEATURE_TRILINEAR_OPTS_STRING_PLAIN      "NVDRS_FEATURE_TRILINEAR_OPTS"
#define NVDRS_FEATURE_TRILINEAR_OPTS_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_TRILINEAR_OPTS_DEFAULT           NVDRS_FEATURE_TRILINEAR_OPTS_NAMESPACE::OFF
#define NVDRS_FEATURE_TRILINEAR_OPTS_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_TRILINEAR_OPTS_NAMESPACE
{
    enum NVDRS_FEATURE_TRILINEAR_OPTS_ENUM 
    {
        OFF = 0x00000000,
        DISABLED = 0x00000000,
        ON = 0x00000001,
        ENABLED = 0x00000001
    };
}


#define NVDRS_FEATURE_TRIPPLE_BUFFERING_PREFIX            "_"
#define NVDRS_FEATURE_TRIPPLE_BUFFERING_STRING            ""
#define NVDRS_FEATURE_TRIPPLE_BUFFERING_ID                0xa010001c
#define NVDRS_FEATURE_TRIPPLE_BUFFERING_STRING_PLAIN      "NVDRS_FEATURE_TRIPPLE_BUFFERING"
#define NVDRS_FEATURE_TRIPPLE_BUFFERING_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_TRIPPLE_BUFFERING_DEFAULT           NVDRS_FEATURE_TRIPPLE_BUFFERING_NAMESPACE::DISABLED
#define NVDRS_FEATURE_TRIPPLE_BUFFERING_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_TRIPPLE_BUFFERING_NAMESPACE
{
    enum NVDRS_FEATURE_TRIPPLE_BUFFERING_ENUM 
    {
        DISABLED = 0x00000000,
        ENABLED = 0x00000001
    };
}


#define NVDRS_FEATURE_VRPRERENDER_LIMIT_PREFIX            "_"
#define NVDRS_FEATURE_VRPRERENDER_LIMIT_STRING            ""
#define NVDRS_FEATURE_VRPRERENDER_LIMIT_ID                0xa010001e
#define NVDRS_FEATURE_VRPRERENDER_LIMIT_STRING_PLAIN      "NVDRS_FEATURE_VRPRERENDER_LIMIT"
#define NVDRS_FEATURE_VRPRERENDER_LIMIT_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_VRPRERENDER_LIMIT_DEFAULT           NVDRS_FEATURE_VRPRERENDER_LIMIT_NAMESPACE::ONE
#define NVDRS_FEATURE_VRPRERENDER_LIMIT_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_VRPRERENDER_LIMIT_NAMESPACE
{
    enum NVDRS_FEATURE_VRPRERENDER_LIMIT_ENUM 
    {
        MIN = 0x00,
        MAX = 0xff,
        APP_CONTROLLED = 0x00,
        NONE = 0,
        ONE = 1,
        TWO = 2,
        THREE = 3,
        FOUR = 4,
        FIVE = 5,
        SIX = 6,
        SEVEN = 7,
        EIGHT = 8
    };
}


#define NVDRS_FEATURE_VSYNC_PREFIX            "_"
#define NVDRS_FEATURE_VSYNC_STRING            ""
#define NVDRS_FEATURE_VSYNC_ID                0xa010001d
#define NVDRS_FEATURE_VSYNC_STRING_PLAIN      "NVDRS_FEATURE_VSYNC"
#define NVDRS_FEATURE_VSYNC_OVERINSTALL       0 // OVERRIDE
#define NVDRS_FEATURE_VSYNC_DEFAULT           NVDRS_FEATURE_VSYNC_NAMESPACE::APPCONTROLLED
#define NVDRS_FEATURE_VSYNC_APP_PROFILE_ENUM  EN_NONE
namespace NVDRS_FEATURE_VSYNC_NAMESPACE
{
    enum NVDRS_FEATURE_VSYNC_ENUM 
    {
        APPCONTROLLED = 0,
        FORCEOFF = 1,
        FORCEON = 2,
        FORCEON_INTERVAL2 = 3,
        ADAPTIVE = 4,
        ADAPTIVE_HALF_REFRESH_RATE = 5,
        SMOOTH = 6,
        GSYNC_ENABLE = 7,
        GSYNC_NOT_SUPPORTED = 8
    };
}


