
/* THIS FILE IS AUTO-GENERATED!  DO NOT EDIT!
**
** To modify this file, regenerate after editing
** any RKY file
*/

#if !defined KERNEL_NOTIFICATION_ID_FLAG 
#define KERNEL_NOTIFICATION_ID_FLAG                                    0x01000000
#define NEEDS_KERNEL_NOTIFICATION(id)                                  (id & KERNEL_NOTIFICATION_ID_FLAG)
#endif // KERNEL_NOTIFICATION_ID_FLAG 

#define AUDIO_INJECT_RXINPUT_DLL_PREFIX            "_"
#define AUDIO_INJECT_RXINPUT_DLL_STRING            ""
#define AUDIO_INJECT_RXINPUT_DLL_ID                0x80303a19
#define AUDIO_INJECT_RXINPUT_DLL_STRING_PLAIN      "AUDIO_INJECT_RXINPUT_DLL"
#define AUDIO_INJECT_RXINPUT_DLL_OVERINSTALL       0 // OVERRIDE
#define AUDIO_INJECT_RXINPUT_DLL_DEFAULT           AUDIO_INJECT_RXINPUT_DLL_NAMESPACE::ON
#define AUDIO_INJECT_RXINPUT_DLL_APP_PROFILE_ENUM  EN_NONE
namespace AUDIO_INJECT_RXINPUT_DLL_NAMESPACE
{
    enum AUDIO_INJECT_RXINPUT_DLL_ENUM 
    {
        OFF = 0x00000000,
        DISABLED = 0x00000000,
        ON = 0x00000001,
        ENABLED = 0x00000001
    };
}


#define GFE_ADDRESSED_PREFIX            "_"
#define GFE_ADDRESSED_STRING            ""
#define GFE_ADDRESSED_ID                0x80d206b4
#define GFE_ADDRESSED_STRING_PLAIN      "GFE_ADDRESSED"
#define GFE_ADDRESSED_OVERINSTALL       0 // OVERRIDE
#define GFE_ADDRESSED_DEFAULT           GFE_ADDRESSED_NAMESPACE::OFF
#define GFE_ADDRESSED_APP_PROFILE_ENUM  EN_NONE
namespace GFE_ADDRESSED_NAMESPACE
{
    enum GFE_ADDRESSED_ENUM 
    {
        OFF = 0x00000000,
        DISABLED = 0x00000000,
        ON = 0x00000001,
        ENABLED = 0x00000001
    };
}


#define GFE_DISPLAY_IN_UI_PREFIX            "_"
#define GFE_DISPLAY_IN_UI_STRING            ""
#define GFE_DISPLAY_IN_UI_ID                0x80303e0e
#define GFE_DISPLAY_IN_UI_STRING_PLAIN      "GFE_DISPLAY_IN_UI"
#define GFE_DISPLAY_IN_UI_OVERINSTALL       0 // OVERRIDE
#define GFE_DISPLAY_IN_UI_DEFAULT           GFE_DISPLAY_IN_UI_NAMESPACE::OFF
#define GFE_DISPLAY_IN_UI_APP_PROFILE_ENUM  EN_NONE
namespace GFE_DISPLAY_IN_UI_NAMESPACE
{
    enum GFE_DISPLAY_IN_UI_ENUM 
    {
        OFF = 0x00000000,
        DISABLED = 0x00000000,
        ON = 0x00000001,
        ENABLED = 0x00000001
    };
}


#define GFE_GAMESESSION_TELEMETRY_REDESIGN_PREFIX            "_"
#define GFE_GAMESESSION_TELEMETRY_REDESIGN_STRING            ""
#define GFE_GAMESESSION_TELEMETRY_REDESIGN_ID                0x80303e0f
#define GFE_GAMESESSION_TELEMETRY_REDESIGN_STRING_PLAIN      "GFE_GAMESESSION_TELEMETRY_REDESIGN"
#define GFE_GAMESESSION_TELEMETRY_REDESIGN_OVERINSTALL       0 // OVERRIDE
#define GFE_GAMESESSION_TELEMETRY_REDESIGN_DEFAULT           GFE_GAMESESSION_TELEMETRY_REDESIGN_NAMESPACE::OFF
#define GFE_GAMESESSION_TELEMETRY_REDESIGN_APP_PROFILE_ENUM  EN_NONE
namespace GFE_GAMESESSION_TELEMETRY_REDESIGN_NAMESPACE
{
    enum GFE_GAMESESSION_TELEMETRY_REDESIGN_ENUM 
    {
        OFF = 0x00000000,
        DISABLED = 0x00000000,
        ON = 0x00000001,
        ENABLED = 0x00000001
    };
}


#define GFE_MONITOR_USAGE_PREFIX            "_"
#define GFE_MONITOR_USAGE_STRING            ""
#define GFE_MONITOR_USAGE_ID                0x80857a28
#define GFE_MONITOR_USAGE_STRING_PLAIN      "GFE_MONITOR_USAGE"
#define GFE_MONITOR_USAGE_OVERINSTALL       0 // OVERRIDE
#define GFE_MONITOR_USAGE_DEFAULT           GFE_MONITOR_USAGE_NAMESPACE::OFF
#define GFE_MONITOR_USAGE_APP_PROFILE_ENUM  EN_NONE
namespace GFE_MONITOR_USAGE_NAMESPACE
{
    enum GFE_MONITOR_USAGE_ENUM 
    {
        OFF = 0x00000000,
        DISABLED = 0x00000000,
        ON = 0x00000001,
        ENABLED = 0x00000001
    };
}


#define GFE_SUPPORTED_PREFIX            "_"
#define GFE_SUPPORTED_STRING            ""
#define GFE_SUPPORTED_ID                0x801dc1b0
#define GFE_SUPPORTED_STRING_PLAIN      "GFE_SUPPORTED"
#define GFE_SUPPORTED_OVERINSTALL       0 // OVERRIDE
#define GFE_SUPPORTED_DEFAULT           GFE_SUPPORTED_NAMESPACE::OFF
#define GFE_SUPPORTED_APP_PROFILE_ENUM  EN_NONE
namespace GFE_SUPPORTED_NAMESPACE
{
    enum GFE_SUPPORTED_ENUM 
    {
        OFF = 0x00000000,
        DISABLED = 0x00000000,
        ON = 0x00000001,
        ENABLED = 0x00000001
    };
}


#define SHADOWPLAY_FLAGS_PREFIX            "_"
#define SHADOWPLAY_FLAGS_STRING            ""
#define SHADOWPLAY_FLAGS_ID                0x809d5f60
#define SHADOWPLAY_FLAGS_STRING_PLAIN      "SHADOWPLAY_FLAGS"
#define SHADOWPLAY_FLAGS_OVERINSTALL       0 // OVERRIDE
#define SHADOWPLAY_FLAGS_DEFAULT           0x00000001
#define SHADOWPLAY_FLAGS_APP_PROFILE_ENUM  EN_NONE


