
/* THIS FILE IS AUTO-GENERATED!  DO NOT EDIT!
**
** To modify this file, regenerate after editing
** any RKY file
*/

#if !defined KERNEL_NOTIFICATION_ID_FLAG 
#define KERNEL_NOTIFICATION_ID_FLAG                                    0x01000000
#define NEEDS_KERNEL_NOTIFICATION(id)                                  (id & KERNEL_NOTIFICATION_ID_FLAG)
#endif // KERNEL_NOTIFICATION_ID_FLAG 

#define STEREO_2DDCONVERGENCE_PREFIX            "_"
#define STEREO_2DDCONVERGENCE_STRING            ""
#define STEREO_2DDCONVERGENCE_ID                0x709adadb
#define STEREO_2DDCONVERGENCE_STRING_PLAIN      "STEREO_2DDCONVERGENCE"
#define STEREO_2DDCONVERGENCE_OVERINSTALL       0 // OVERRIDE
#define STEREO_2DDCONVERGENCE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_2DDHUDSETTINGS_PREFIX            "_"
#define STEREO_2DDHUDSETTINGS_STRING            ""
#define STEREO_2DDHUDSETTINGS_ID                0x709adada
#define STEREO_2DDHUDSETTINGS_STRING_PLAIN      "STEREO_2DDHUDSETTINGS"
#define STEREO_2DDHUDSETTINGS_OVERINSTALL       0 // OVERRIDE
#define STEREO_2DDHUDSETTINGS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_2DD_NOTES_PREFIX            "_"
#define STEREO_2DD_NOTES_STRING            ""
#define STEREO_2DD_NOTES_ID                0x709adadc
#define STEREO_2DD_NOTES_STRING_PLAIN      "STEREO_2DD_NOTES"
#define STEREO_2DD_NOTES_OVERINSTALL       0 // OVERRIDE
#define STEREO_2DD_NOTES_APP_PROFILE_ENUM  EN_NONE


#define STEREO_ALLOWNONEXCLUSIVESTEREO_PREFIX            "_"
#define STEREO_ALLOWNONEXCLUSIVESTEREO_STRING            ""
#define STEREO_ALLOWNONEXCLUSIVESTEREO_ID                0x702c7709
#define STEREO_ALLOWNONEXCLUSIVESTEREO_STRING_PLAIN      "STEREO_ALLOWNONEXCLUSIVESTEREO"
#define STEREO_ALLOWNONEXCLUSIVESTEREO_OVERINSTALL       0 // OVERRIDE
#define STEREO_ALLOWNONEXCLUSIVESTEREO_APP_PROFILE_ENUM  EN_NONE


#define STEREO_API_PREFIX            "_"
#define STEREO_API_STRING            ""
#define STEREO_API_ID                0x70b5603f
#define STEREO_API_STRING_PLAIN      "STEREO_API"
#define STEREO_API_OVERINSTALL       0 // OVERRIDE
#define STEREO_API_APP_PROFILE_ENUM  EN_NONE


#define STEREO_AUTOCONVERGENCE_PREFIX            "_"
#define STEREO_AUTOCONVERGENCE_STRING            ""
#define STEREO_AUTOCONVERGENCE_ID                0x702a0ab2
#define STEREO_AUTOCONVERGENCE_STRING_PLAIN      "STEREO_AUTOCONVERGENCE"
#define STEREO_AUTOCONVERGENCE_OVERINSTALL       0 // OVERRIDE
#define STEREO_AUTOCONVERGENCE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_AUTOCONVERGENCEADJUSTPACE_PREFIX            "_"
#define STEREO_AUTOCONVERGENCEADJUSTPACE_STRING            ""
#define STEREO_AUTOCONVERGENCEADJUSTPACE_ID                0x70bf3c6b
#define STEREO_AUTOCONVERGENCEADJUSTPACE_STRING_PLAIN      "STEREO_AUTOCONVERGENCEADJUSTPACE"
#define STEREO_AUTOCONVERGENCEADJUSTPACE_OVERINSTALL       0 // OVERRIDE
#define STEREO_AUTOCONVERGENCEADJUSTPACE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_COMPAREEYES_PREFIX            "_"
#define STEREO_COMPAREEYES_STRING            ""
#define STEREO_COMPAREEYES_ID                0x70729e58
#define STEREO_COMPAREEYES_STRING_PLAIN      "STEREO_COMPAREEYES"
#define STEREO_COMPAREEYES_OVERINSTALL       0 // OVERRIDE
#define STEREO_COMPAREEYES_APP_PROFILE_ENUM  EN_NONE


#define STEREO_COMPAREFROM_PREFIX            "_"
#define STEREO_COMPAREFROM_STRING            ""
#define STEREO_COMPAREFROM_ID                0x70efb726
#define STEREO_COMPAREFROM_STRING_PLAIN      "STEREO_COMPAREFROM"
#define STEREO_COMPAREFROM_OVERINSTALL       0 // OVERRIDE
#define STEREO_COMPAREFROM_APP_PROFILE_ENUM  EN_NONE


#define STEREO_COMPAT_PREFIX            "_"
#define STEREO_COMPAT_STRING            ""
#define STEREO_COMPAT_ID                0x7051e5f5
#define STEREO_COMPAT_STRING_PLAIN      "STEREO_COMPAT"
#define STEREO_COMPAT_OVERINSTALL       0 // OVERRIDE
#define STEREO_COMPAT_APP_PROFILE_ENUM  EN_NONE


#define STEREO_CONFIG_PREFIX            "_"
#define STEREO_CONFIG_STRING            ""
#define STEREO_CONFIG_ID                0x70ec1071
#define STEREO_CONFIG_STRING_PLAIN      "STEREO_CONFIG"
#define STEREO_CONFIG_OVERINSTALL       0 // OVERRIDE
#define STEREO_CONFIG_APP_PROFILE_ENUM  EN_NONE


#define STEREO_CUTOFFFARDEPTHLESS_PREFIX            "_"
#define STEREO_CUTOFFFARDEPTHLESS_STRING            ""
#define STEREO_CUTOFFFARDEPTHLESS_ID                0x704c9a46
#define STEREO_CUTOFFFARDEPTHLESS_STRING_PLAIN      "STEREO_CUTOFFFARDEPTHLESS"
#define STEREO_CUTOFFFARDEPTHLESS_OVERINSTALL       0 // OVERRIDE
#define STEREO_CUTOFFFARDEPTHLESS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_CUTOFFFARDEPTHMORE_PREFIX            "_"
#define STEREO_CUTOFFFARDEPTHMORE_STRING            ""
#define STEREO_CUTOFFFARDEPTHMORE_ID                0x70fbc04d
#define STEREO_CUTOFFFARDEPTHMORE_STRING_PLAIN      "STEREO_CUTOFFFARDEPTHMORE"
#define STEREO_CUTOFFFARDEPTHMORE_OVERINSTALL       0 // OVERRIDE
#define STEREO_CUTOFFFARDEPTHMORE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_CUTOFFNEARDEPTHLESS_PREFIX            "_"
#define STEREO_CUTOFFNEARDEPTHLESS_STRING            ""
#define STEREO_CUTOFFNEARDEPTHLESS_ID                0x70d1bdb5
#define STEREO_CUTOFFNEARDEPTHLESS_STRING_PLAIN      "STEREO_CUTOFFNEARDEPTHLESS"
#define STEREO_CUTOFFNEARDEPTHLESS_OVERINSTALL       0 // OVERRIDE
#define STEREO_CUTOFFNEARDEPTHLESS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_CUTOFFNEARDEPTHMORE_PREFIX            "_"
#define STEREO_CUTOFFNEARDEPTHMORE_STRING            ""
#define STEREO_CUTOFFNEARDEPTHMORE_ID                0x7020c991
#define STEREO_CUTOFFNEARDEPTHMORE_STRING_PLAIN      "STEREO_CUTOFFNEARDEPTHMORE"
#define STEREO_CUTOFFNEARDEPTHMORE_OVERINSTALL       0 // OVERRIDE
#define STEREO_CUTOFFNEARDEPTHMORE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_CUTOFFSTEPLESS_PREFIX            "_"
#define STEREO_CUTOFFSTEPLESS_STRING            ""
#define STEREO_CUTOFFSTEPLESS_ID                0x704b45c7
#define STEREO_CUTOFFSTEPLESS_STRING_PLAIN      "STEREO_CUTOFFSTEPLESS"
#define STEREO_CUTOFFSTEPLESS_OVERINSTALL       0 // OVERRIDE
#define STEREO_CUTOFFSTEPLESS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_CUTOFFSTEPMORE_PREFIX            "_"
#define STEREO_CUTOFFSTEPMORE_STRING            ""
#define STEREO_CUTOFFSTEPMORE_ID                0x700f2971
#define STEREO_CUTOFFSTEPMORE_STRING_PLAIN      "STEREO_CUTOFFSTEPMORE"
#define STEREO_CUTOFFSTEPMORE_OVERINSTALL       0 // OVERRIDE
#define STEREO_CUTOFFSTEPMORE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_D_PREFIX            "_"
#define STEREO_D_STRING            ""
#define STEREO_D_ID                0x708ec205
#define STEREO_D_STRING_PLAIN      "STEREO_D"
#define STEREO_D_OVERINSTALL       0 // OVERRIDE
#define STEREO_D_APP_PROFILE_ENUM  EN_NONE


#define STEREO_DATE_REL_PREFIX            "_"
#define STEREO_DATE_REL_STRING            ""
#define STEREO_DATE_REL_ID                0x705fafec
#define STEREO_DATE_REL_STRING_PLAIN      "STEREO_DATE_REL"
#define STEREO_DATE_REL_OVERINSTALL       0 // OVERRIDE
#define STEREO_DATE_REL_APP_PROFILE_ENUM  EN_NONE


#define STEREO_DELAYEDSTEREODESKTOP_PREFIX            "_"
#define STEREO_DELAYEDSTEREODESKTOP_STRING            ""
#define STEREO_DELAYEDSTEREODESKTOP_ID                0x7042eef1
#define STEREO_DELAYEDSTEREODESKTOP_STRING_PLAIN      "STEREO_DELAYEDSTEREODESKTOP"
#define STEREO_DELAYEDSTEREODESKTOP_OVERINSTALL       0 // OVERRIDE
#define STEREO_DELAYEDSTEREODESKTOP_APP_PROFILE_ENUM  EN_NONE


#define STEREO_DELAYED_BY_PRESENTS_PREFIX            "_"
#define STEREO_DELAYED_BY_PRESENTS_STRING            ""
#define STEREO_DELAYED_BY_PRESENTS_ID                0x70a7fc7f
#define STEREO_DELAYED_BY_PRESENTS_STRING_PLAIN      "STEREO_DELAYED_BY_PRESENTS"
#define STEREO_DELAYED_BY_PRESENTS_OVERINSTALL       0 // OVERRIDE
#define STEREO_DELAYED_BY_PRESENTS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_DELETECONFIG_PREFIX            "_"
#define STEREO_DELETECONFIG_STRING            ""
#define STEREO_DELETECONFIG_ID                0x70c73ba2
#define STEREO_DELETECONFIG_STRING_PLAIN      "STEREO_DELETECONFIG"
#define STEREO_DELETECONFIG_OVERINSTALL       0 // OVERRIDE
#define STEREO_DELETECONFIG_APP_PROFILE_ENUM  EN_NONE


#define STEREO_DEVELOPER_PREFIX            "_"
#define STEREO_DEVELOPER_STRING            ""
#define STEREO_DEVELOPER_ID                0x703c4026
#define STEREO_DEVELOPER_STRING_PLAIN      "STEREO_DEVELOPER"
#define STEREO_DEVELOPER_OVERINSTALL       0 // OVERRIDE
#define STEREO_DEVELOPER_APP_PROFILE_ENUM  EN_NONE


#define STEREO_DEVELOPER_ISSUES_PREFIX            "_"
#define STEREO_DEVELOPER_ISSUES_STRING            ""
#define STEREO_DEVELOPER_ISSUES_ID                0x704f5928
#define STEREO_DEVELOPER_ISSUES_STRING_PLAIN      "STEREO_DEVELOPER_ISSUES"
#define STEREO_DEVELOPER_ISSUES_OVERINSTALL       0 // OVERRIDE
#define STEREO_DEVELOPER_ISSUES_APP_PROFILE_ENUM  EN_NONE


#define STEREO_DISABLEONOUTOFMEMORY_PREFIX            "_"
#define STEREO_DISABLEONOUTOFMEMORY_STRING            ""
#define STEREO_DISABLEONOUTOFMEMORY_ID                0x70c71508
#define STEREO_DISABLEONOUTOFMEMORY_STRING_PLAIN      "STEREO_DISABLEONOUTOFMEMORY"
#define STEREO_DISABLEONOUTOFMEMORY_OVERINSTALL       0 // OVERRIDE
#define STEREO_DISABLEONOUTOFMEMORY_APP_PROFILE_ENUM  EN_NONE


#define STEREO_DISABLE_2DD_PREFIX            "_"
#define STEREO_DISABLE_2DD_STRING            ""
#define STEREO_DISABLE_2DD_ID                0x709adadd
#define STEREO_DISABLE_2DD_STRING_PLAIN      "STEREO_DISABLE_2DD"
#define STEREO_DISABLE_2DD_OVERINSTALL       0 // OVERRIDE
#define STEREO_DISABLE_2DD_APP_PROFILE_ENUM  EN_NONE


#define STEREO_DISCARDHOTKEYS_PREFIX            "_"
#define STEREO_DISCARDHOTKEYS_STRING            ""
#define STEREO_DISCARDHOTKEYS_ID                0x70175566
#define STEREO_DISCARDHOTKEYS_STRING_PLAIN      "STEREO_DISCARDHOTKEYS"
#define STEREO_DISCARDHOTKEYS_OVERINSTALL       0 // OVERRIDE
#define STEREO_DISCARDHOTKEYS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_DX10DSCBNUMBER_PREFIX            "_"
#define STEREO_DX10DSCBNUMBER_STRING            ""
#define STEREO_DX10DSCBNUMBER_ID                0x70092d4a
#define STEREO_DX10DSCBNUMBER_STRING_PLAIN      "STEREO_DX10DSCBNUMBER"
#define STEREO_DX10DSCBNUMBER_OVERINSTALL       0 // OVERRIDE
#define STEREO_DX10DSCBNUMBER_APP_PROFILE_ENUM  EN_NONE


#define STEREO_DX10VSCBNUMBER_PREFIX            "_"
#define STEREO_DX10VSCBNUMBER_STRING            ""
#define STEREO_DX10VSCBNUMBER_ID                0x70f8e408
#define STEREO_DX10VSCBNUMBER_STRING_PLAIN      "STEREO_DX10VSCBNUMBER"
#define STEREO_DX10VSCBNUMBER_OVERINSTALL       0 // OVERRIDE
#define STEREO_DX10VSCBNUMBER_APP_PROFILE_ENUM  EN_NONE


#define STEREO_DX10VSCBNUMBER_DX11_PREFIX            "_"
#define STEREO_DX10VSCBNUMBER_DX11_STRING            ""
#define STEREO_DX10VSCBNUMBER_DX11_ID                0x70f64a32
#define STEREO_DX10VSCBNUMBER_DX11_STRING_PLAIN      "STEREO_DX10VSCBNUMBER_DX11"
#define STEREO_DX10VSCBNUMBER_DX11_OVERINSTALL       0 // OVERRIDE
#define STEREO_DX10VSCBNUMBER_DX11_APP_PROFILE_ENUM  EN_NONE


#define STEREO_D_EXE_NAME_PREFIX            "_"
#define STEREO_D_EXE_NAME_STRING            ""
#define STEREO_D_EXE_NAME_ID                0x70d8bd43
#define STEREO_D_EXE_NAME_STRING_PLAIN      "STEREO_D_EXE_NAME"
#define STEREO_D_EXE_NAME_OVERINSTALL       0 // OVERRIDE
#define STEREO_D_EXE_NAME_APP_PROFILE_ENUM  EN_NONE


#define STEREO_ENABLECE_PREFIX            "_"
#define STEREO_ENABLECE_STRING            ""
#define STEREO_ENABLECE_ID                0x702b8c95
#define STEREO_ENABLECE_STRING_PLAIN      "STEREO_ENABLECE"
#define STEREO_ENABLECE_OVERINSTALL       0 // OVERRIDE
#define STEREO_ENABLECE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_ENABLECONSUMERSTEREOSUPPORT_PREFIX            "_"
#define STEREO_ENABLECONSUMERSTEREOSUPPORT_STRING            ""
#define STEREO_ENABLECONSUMERSTEREOSUPPORT_ID                0x70cb9168
#define STEREO_ENABLECONSUMERSTEREOSUPPORT_STRING_PLAIN      "STEREO_ENABLECONSUMERSTEREOSUPPORT"
#define STEREO_ENABLECONSUMERSTEREOSUPPORT_OVERINSTALL       0 // OVERRIDE
#define STEREO_ENABLECONSUMERSTEREOSUPPORT_APP_PROFILE_ENUM  EN_NONE


#define STEREO_ENABLEPARTIALSTEREOBLIT_PREFIX            "_"
#define STEREO_ENABLEPARTIALSTEREOBLIT_STRING            ""
#define STEREO_ENABLEPARTIALSTEREOBLIT_ID                0x7096eced
#define STEREO_ENABLEPARTIALSTEREOBLIT_STRING_PLAIN      "STEREO_ENABLEPARTIALSTEREOBLIT"
#define STEREO_ENABLEPARTIALSTEREOBLIT_OVERINSTALL       0 // OVERRIDE
#define STEREO_ENABLEPARTIALSTEREOBLIT_APP_PROFILE_ENUM  EN_NONE


#define STEREO_FAVORSZ_PREFIX            "_"
#define STEREO_FAVORSZ_STRING            ""
#define STEREO_FAVORSZ_ID                0x705faed7
#define STEREO_FAVORSZ_STRING_PLAIN      "STEREO_FAVORSZ"
#define STEREO_FAVORSZ_OVERINSTALL       0 // OVERRIDE
#define STEREO_FAVORSZ_APP_PROFILE_ENUM  EN_NONE


#define STEREO_FRUSTUMADJUSTMODE_PREFIX            "_"
#define STEREO_FRUSTUMADJUSTMODE_STRING            ""
#define STEREO_FRUSTUMADJUSTMODE_ID                0x70a1411a
#define STEREO_FRUSTUMADJUSTMODE_STRING_PLAIN      "STEREO_FRUSTUMADJUSTMODE"
#define STEREO_FRUSTUMADJUSTMODE_OVERINSTALL       0 // OVERRIDE
#define STEREO_FRUSTUMADJUSTMODE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_FRUSTUMADJUSTMODE_DX10_PREFIX            "_"
#define STEREO_FRUSTUMADJUSTMODE_DX10_STRING            ""
#define STEREO_FRUSTUMADJUSTMODE_DX10_ID                0x70ed1da7
#define STEREO_FRUSTUMADJUSTMODE_DX10_STRING_PLAIN      "STEREO_FRUSTUMADJUSTMODE_DX10"
#define STEREO_FRUSTUMADJUSTMODE_DX10_OVERINSTALL       0 // OVERRIDE
#define STEREO_FRUSTUMADJUSTMODE_DX10_APP_PROFILE_ENUM  EN_NONE


#define STEREO_FRUSTUMADJUSTMODE_DX11_PREFIX            "_"
#define STEREO_FRUSTUMADJUSTMODE_DX11_STRING            ""
#define STEREO_FRUSTUMADJUSTMODE_DX11_ID                0x70f475a0
#define STEREO_FRUSTUMADJUSTMODE_DX11_STRING_PLAIN      "STEREO_FRUSTUMADJUSTMODE_DX11"
#define STEREO_FRUSTUMADJUSTMODE_DX11_OVERINSTALL       0 // OVERRIDE
#define STEREO_FRUSTUMADJUSTMODE_DX11_APP_PROFILE_ENUM  EN_NONE


#define STEREO_GAME_PREFIX            "_"
#define STEREO_GAME_STRING            ""
#define STEREO_GAME_ID                0x70c8d48e
#define STEREO_GAME_STRING_PLAIN      "STEREO_GAME"
#define STEREO_GAME_OVERINSTALL       0 // OVERRIDE
#define STEREO_GAME_APP_PROFILE_ENUM  EN_NONE


#define STEREO_GAMECONFIGS_PREFIX            "_"
#define STEREO_GAMECONFIGS_STRING            ""
#define STEREO_GAMECONFIGS_ID                0x704a905a
#define STEREO_GAMECONFIGS_STRING_PLAIN      "STEREO_GAMECONFIGS"
#define STEREO_GAMECONFIGS_OVERINSTALL       0 // OVERRIDE
#define STEREO_GAMECONFIGS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_GAMESPECIFIC0_PREFIX            "_"
#define STEREO_GAMESPECIFIC0_STRING            ""
#define STEREO_GAMESPECIFIC0_ID                0x702244b7
#define STEREO_GAMESPECIFIC0_STRING_PLAIN      "STEREO_GAMESPECIFIC0"
#define STEREO_GAMESPECIFIC0_OVERINSTALL       0 // OVERRIDE
#define STEREO_GAMESPECIFIC0_APP_PROFILE_ENUM  EN_NONE


#define STEREO_GAME_ISSUES_PREFIX            "_"
#define STEREO_GAME_ISSUES_STRING            ""
#define STEREO_GAME_ISSUES_ID                0x703cb342
#define STEREO_GAME_ISSUES_STRING_PLAIN      "STEREO_GAME_ISSUES"
#define STEREO_GAME_ISSUES_OVERINSTALL       0 // OVERRIDE
#define STEREO_GAME_ISSUES_APP_PROFILE_ENUM  EN_NONE


#define STEREO_GAME_ISSUE_CODES_PREFIX            "_"
#define STEREO_GAME_ISSUE_CODES_STRING            ""
#define STEREO_GAME_ISSUE_CODES_ID                0x704cde5a
#define STEREO_GAME_ISSUE_CODES_STRING_PLAIN      "STEREO_GAME_ISSUE_CODES"
#define STEREO_GAME_ISSUE_CODES_OVERINSTALL       0 // OVERRIDE
#define STEREO_GAME_ISSUE_CODES_APP_PROFILE_ENUM  EN_NONE


#define STEREO_GAME_RELEASE_PREFIX            "_"
#define STEREO_GAME_RELEASE_STRING            ""
#define STEREO_GAME_RELEASE_ID                0x70c345e6
#define STEREO_GAME_RELEASE_STRING_PLAIN      "STEREO_GAME_RELEASE"
#define STEREO_GAME_RELEASE_OVERINSTALL       0 // OVERRIDE
#define STEREO_GAME_RELEASE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_GAME_SETTINGS_PREFIX            "_"
#define STEREO_GAME_SETTINGS_STRING            ""
#define STEREO_GAME_SETTINGS_ID                0x704d456e
#define STEREO_GAME_SETTINGS_STRING_PLAIN      "STEREO_GAME_SETTINGS"
#define STEREO_GAME_SETTINGS_OVERINSTALL       0 // OVERRIDE
#define STEREO_GAME_SETTINGS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_GAMMAADJUSTLESS_PREFIX            "_"
#define STEREO_GAMMAADJUSTLESS_STRING            ""
#define STEREO_GAMMAADJUSTLESS_ID                0x70e8420c
#define STEREO_GAMMAADJUSTLESS_STRING_PLAIN      "STEREO_GAMMAADJUSTLESS"
#define STEREO_GAMMAADJUSTLESS_OVERINSTALL       0 // OVERRIDE
#define STEREO_GAMMAADJUSTLESS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_GAMMAADJUSTMORE_PREFIX            "_"
#define STEREO_GAMMAADJUSTMORE_STRING            ""
#define STEREO_GAMMAADJUSTMORE_ID                0x703f4521
#define STEREO_GAMMAADJUSTMORE_STRING_PLAIN      "STEREO_GAMMAADJUSTMORE"
#define STEREO_GAMMAADJUSTMORE_OVERINSTALL       0 // OVERRIDE
#define STEREO_GAMMAADJUSTMORE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_GLASSESDELAYMINUS_PREFIX            "_"
#define STEREO_GLASSESDELAYMINUS_STRING            ""
#define STEREO_GLASSESDELAYMINUS_ID                0x70b8a743
#define STEREO_GLASSESDELAYMINUS_STRING_PLAIN      "STEREO_GLASSESDELAYMINUS"
#define STEREO_GLASSESDELAYMINUS_OVERINSTALL       0 // OVERRIDE
#define STEREO_GLASSESDELAYMINUS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_GLASSESDELAYPLUS_PREFIX            "_"
#define STEREO_GLASSESDELAYPLUS_STRING            ""
#define STEREO_GLASSESDELAYPLUS_ID                0x701fc5b4
#define STEREO_GLASSESDELAYPLUS_STRING_PLAIN      "STEREO_GLASSESDELAYPLUS"
#define STEREO_GLASSESDELAYPLUS_OVERINSTALL       0 // OVERRIDE
#define STEREO_GLASSESDELAYPLUS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_GLASSESSWITCHDELAY_PREFIX            "_"
#define STEREO_GLASSESSWITCHDELAY_STRING            ""
#define STEREO_GLASSESSWITCHDELAY_ID                0x70057bb6
#define STEREO_GLASSESSWITCHDELAY_STRING_PLAIN      "STEREO_GLASSESSWITCHDELAY"
#define STEREO_GLASSESSWITCHDELAY_OVERINSTALL       0 // OVERRIDE
#define STEREO_GLASSESSWITCHDELAY_APP_PROFILE_ENUM  EN_NONE


#define STEREO_HOTKEY_FRUSTUMADJUSTMODE_PREFIX            "_"
#define STEREO_HOTKEY_FRUSTUMADJUSTMODE_STRING            ""
#define STEREO_HOTKEY_FRUSTUMADJUSTMODE_ID                0x70d17b31
#define STEREO_HOTKEY_FRUSTUMADJUSTMODE_STRING_PLAIN      "STEREO_HOTKEY_FRUSTUMADJUSTMODE"
#define STEREO_HOTKEY_FRUSTUMADJUSTMODE_OVERINSTALL       0 // OVERRIDE
#define STEREO_HOTKEY_FRUSTUMADJUSTMODE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_INGAMELASERSIGHT_PREFIX            "_"
#define STEREO_INGAMELASERSIGHT_STRING            ""
#define STEREO_INGAMELASERSIGHT_ID                0x7064f0c2
#define STEREO_INGAMELASERSIGHT_STRING_PLAIN      "STEREO_INGAMELASERSIGHT"
#define STEREO_INGAMELASERSIGHT_OVERINSTALL       0 // OVERRIDE
#define STEREO_INGAMELASERSIGHT_APP_PROFILE_ENUM  EN_NONE


#define STEREO_INGAMELASERSIGHTDX9STATES_PREFIX            "_"
#define STEREO_INGAMELASERSIGHTDX9STATES_STRING            ""
#define STEREO_INGAMELASERSIGHTDX9STATES_ID                0x706139ad
#define STEREO_INGAMELASERSIGHTDX9STATES_STRING_PLAIN      "STEREO_INGAMELASERSIGHTDX9STATES"
#define STEREO_INGAMELASERSIGHTDX9STATES_OVERINSTALL       0 // OVERRIDE
#define STEREO_INGAMELASERSIGHTDX9STATES_APP_PROFILE_ENUM  EN_NONE


#define STEREO_INGAMELASERSIGHT_DX10_PREFIX            "_"
#define STEREO_INGAMELASERSIGHT_DX10_STRING            ""
#define STEREO_INGAMELASERSIGHT_DX10_ID                0x70dd2585
#define STEREO_INGAMELASERSIGHT_DX10_STRING_PLAIN      "STEREO_INGAMELASERSIGHT_DX10"
#define STEREO_INGAMELASERSIGHT_DX10_OVERINSTALL       0 // OVERRIDE
#define STEREO_INGAMELASERSIGHT_DX10_APP_PROFILE_ENUM  EN_NONE


#define STEREO_INGAMELASERSIGHT_DX11_PREFIX            "_"
#define STEREO_INGAMELASERSIGHT_DX11_STRING            ""
#define STEREO_INGAMELASERSIGHT_DX11_ID                0x70e7adad
#define STEREO_INGAMELASERSIGHT_DX11_STRING_PLAIN      "STEREO_INGAMELASERSIGHT_DX11"
#define STEREO_INGAMELASERSIGHT_DX11_OVERINSTALL       0 // OVERRIDE
#define STEREO_INGAMELASERSIGHT_DX11_APP_PROFILE_ENUM  EN_NONE


#define STEREO_INTERLEAVEPATTERN0_PREFIX            "_"
#define STEREO_INTERLEAVEPATTERN0_STRING            ""
#define STEREO_INTERLEAVEPATTERN0_ID                0x70b1c8cc
#define STEREO_INTERLEAVEPATTERN0_STRING_PLAIN      "STEREO_INTERLEAVEPATTERN0"
#define STEREO_INTERLEAVEPATTERN0_OVERINSTALL       0 // OVERRIDE
#define STEREO_INTERLEAVEPATTERN0_APP_PROFILE_ENUM  EN_NONE


#define STEREO_INTERLEAVEPATTERN1_PREFIX            "_"
#define STEREO_INTERLEAVEPATTERN1_STRING            ""
#define STEREO_INTERLEAVEPATTERN1_ID                0x7091a772
#define STEREO_INTERLEAVEPATTERN1_STRING_PLAIN      "STEREO_INTERLEAVEPATTERN1"
#define STEREO_INTERLEAVEPATTERN1_OVERINSTALL       0 // OVERRIDE
#define STEREO_INTERLEAVEPATTERN1_APP_PROFILE_ENUM  EN_NONE


#define STEREO_LASERADJUSTXMINUS_PREFIX            "_"
#define STEREO_LASERADJUSTXMINUS_STRING            ""
#define STEREO_LASERADJUSTXMINUS_ID                0x7048b7dc
#define STEREO_LASERADJUSTXMINUS_STRING_PLAIN      "STEREO_LASERADJUSTXMINUS"
#define STEREO_LASERADJUSTXMINUS_OVERINSTALL       0 // OVERRIDE
#define STEREO_LASERADJUSTXMINUS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_LASERADJUSTXPLUS_PREFIX            "_"
#define STEREO_LASERADJUSTXPLUS_STRING            ""
#define STEREO_LASERADJUSTXPLUS_ID                0x70d8bae6
#define STEREO_LASERADJUSTXPLUS_STRING_PLAIN      "STEREO_LASERADJUSTXPLUS"
#define STEREO_LASERADJUSTXPLUS_OVERINSTALL       0 // OVERRIDE
#define STEREO_LASERADJUSTXPLUS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_LASERADJUSTYMINUS_PREFIX            "_"
#define STEREO_LASERADJUSTYMINUS_STRING            ""
#define STEREO_LASERADJUSTYMINUS_ID                0x70fb9e1e
#define STEREO_LASERADJUSTYMINUS_STRING_PLAIN      "STEREO_LASERADJUSTYMINUS"
#define STEREO_LASERADJUSTYMINUS_OVERINSTALL       0 // OVERRIDE
#define STEREO_LASERADJUSTYMINUS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_LASERADJUSTYPLUS_PREFIX            "_"
#define STEREO_LASERADJUSTYPLUS_STRING            ""
#define STEREO_LASERADJUSTYPLUS_ID                0x7024eda4
#define STEREO_LASERADJUSTYPLUS_STRING_PLAIN      "STEREO_LASERADJUSTYPLUS"
#define STEREO_LASERADJUSTYPLUS_OVERINSTALL       0 // OVERRIDE
#define STEREO_LASERADJUSTYPLUS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_LASERSIGHT_PREFIX            "_"
#define STEREO_LASERSIGHT_STRING            ""
#define STEREO_LASERSIGHT_ID                0x7058b6e1
#define STEREO_LASERSIGHT_STRING_PLAIN      "STEREO_LASERSIGHT"
#define STEREO_LASERSIGHT_OVERINSTALL       0 // OVERRIDE
#define STEREO_LASERSIGHT_APP_PROFILE_ENUM  EN_NONE


#define STEREO_LASERSIGHTENABLED_PREFIX            "_"
#define STEREO_LASERSIGHTENABLED_STRING            ""
#define STEREO_LASERSIGHTENABLED_ID                0x7054837a
#define STEREO_LASERSIGHTENABLED_STRING_PLAIN      "STEREO_LASERSIGHTENABLED"
#define STEREO_LASERSIGHTENABLED_OVERINSTALL       0 // OVERRIDE
#define STEREO_LASERSIGHTENABLED_APP_PROFILE_ENUM  EN_NONE


#define STEREO_LASERSIGHTFILE_PREFIX            "_"
#define STEREO_LASERSIGHTFILE_STRING            ""
#define STEREO_LASERSIGHTFILE_ID                0x707ac50d
#define STEREO_LASERSIGHTFILE_STRING_PLAIN      "STEREO_LASERSIGHTFILE"
#define STEREO_LASERSIGHTFILE_OVERINSTALL       0 // OVERRIDE
#define STEREO_LASERSIGHTFILE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_LASERSIGHTINDEX_PREFIX            "_"
#define STEREO_LASERSIGHTINDEX_STRING            ""
#define STEREO_LASERSIGHTINDEX_ID                0x70da83c6
#define STEREO_LASERSIGHTINDEX_STRING_PLAIN      "STEREO_LASERSIGHTINDEX"
#define STEREO_LASERSIGHTINDEX_OVERINSTALL       0 // OVERRIDE
#define STEREO_LASERSIGHTINDEX_APP_PROFILE_ENUM  EN_NONE


#define STEREO_LASERSIGHTPROPERTY_PREFIX            "_"
#define STEREO_LASERSIGHTPROPERTY_STRING            ""
#define STEREO_LASERSIGHTPROPERTY_ID                0x7032243a
#define STEREO_LASERSIGHTPROPERTY_STRING_PLAIN      "STEREO_LASERSIGHTPROPERTY"
#define STEREO_LASERSIGHTPROPERTY_OVERINSTALL       0 // OVERRIDE
#define STEREO_LASERSIGHTPROPERTY_APP_PROFILE_ENUM  EN_NONE


#define STEREO_LASERSIGHTTRIGGER_PREFIX            "_"
#define STEREO_LASERSIGHTTRIGGER_STRING            ""
#define STEREO_LASERSIGHTTRIGGER_ID                0x70031b88
#define STEREO_LASERSIGHTTRIGGER_STRING_PLAIN      "STEREO_LASERSIGHTTRIGGER"
#define STEREO_LASERSIGHTTRIGGER_OVERINSTALL       0 // OVERRIDE
#define STEREO_LASERSIGHTTRIGGER_APP_PROFILE_ENUM  EN_NONE


#define STEREO_LASERSIGHT_DX10_PREFIX            "_"
#define STEREO_LASERSIGHT_DX10_STRING            ""
#define STEREO_LASERSIGHT_DX10_ID                0x7031a2e7
#define STEREO_LASERSIGHT_DX10_STRING_PLAIN      "STEREO_LASERSIGHT_DX10"
#define STEREO_LASERSIGHT_DX10_OVERINSTALL       0 // OVERRIDE
#define STEREO_LASERSIGHT_DX10_APP_PROFILE_ENUM  EN_NONE


#define STEREO_LASERSIGHT_DX11_PREFIX            "_"
#define STEREO_LASERSIGHT_DX11_STRING            ""
#define STEREO_LASERSIGHT_DX11_ID                0x7045b752
#define STEREO_LASERSIGHT_DX11_STRING_PLAIN      "STEREO_LASERSIGHT_DX11"
#define STEREO_LASERSIGHT_DX11_OVERINSTALL       0 // OVERRIDE
#define STEREO_LASERSIGHT_DX11_APP_PROFILE_ENUM  EN_NONE


#define STEREO_LASERXADJUST_PREFIX            "_"
#define STEREO_LASERXADJUST_STRING            ""
#define STEREO_LASERXADJUST_ID                0x7057e831
#define STEREO_LASERXADJUST_STRING_PLAIN      "STEREO_LASERXADJUST"
#define STEREO_LASERXADJUST_OVERINSTALL       0 // OVERRIDE
#define STEREO_LASERXADJUST_APP_PROFILE_ENUM  EN_NONE


#define STEREO_LASERYADJUST_PREFIX            "_"
#define STEREO_LASERYADJUST_STRING            ""
#define STEREO_LASERYADJUST_ID                0x70225308
#define STEREO_LASERYADJUST_STRING_PLAIN      "STEREO_LASERYADJUST"
#define STEREO_LASERYADJUST_OVERINSTALL       0 // OVERRIDE
#define STEREO_LASERYADJUST_APP_PROFILE_ENUM  EN_NONE


#define STEREO_LASERZADJUST_PREFIX            "_"
#define STEREO_LASERZADJUST_STRING            ""
#define STEREO_LASERZADJUST_ID                0x7014fca2
#define STEREO_LASERZADJUST_STRING_PLAIN      "STEREO_LASERZADJUST"
#define STEREO_LASERZADJUST_OVERINSTALL       0 // OVERRIDE
#define STEREO_LASERZADJUST_APP_PROFILE_ENUM  EN_NONE


#define STEREO_LEFTANAGLYPHFILTER_PREFIX            "_"
#define STEREO_LEFTANAGLYPHFILTER_STRING            ""
#define STEREO_LEFTANAGLYPHFILTER_ID                0x70d51cd1
#define STEREO_LEFTANAGLYPHFILTER_STRING_PLAIN      "STEREO_LEFTANAGLYPHFILTER"
#define STEREO_LEFTANAGLYPHFILTER_OVERINSTALL       0 // OVERRIDE
#define STEREO_LEFTANAGLYPHFILTER_APP_PROFILE_ENUM  EN_NONE


#define STEREO_LEFTCOLORFILTER0_PREFIX            "_"
#define STEREO_LEFTCOLORFILTER0_STRING            ""
#define STEREO_LEFTCOLORFILTER0_ID                0x70ac6888
#define STEREO_LEFTCOLORFILTER0_STRING_PLAIN      "STEREO_LEFTCOLORFILTER0"
#define STEREO_LEFTCOLORFILTER0_OVERINSTALL       0 // OVERRIDE
#define STEREO_LEFTCOLORFILTER0_APP_PROFILE_ENUM  EN_NONE


#define STEREO_LEFTCOLORFILTER1_PREFIX            "_"
#define STEREO_LEFTCOLORFILTER1_STRING            ""
#define STEREO_LEFTCOLORFILTER1_ID                0x7090b6ca
#define STEREO_LEFTCOLORFILTER1_STRING_PLAIN      "STEREO_LEFTCOLORFILTER1"
#define STEREO_LEFTCOLORFILTER1_OVERINSTALL       0 // OVERRIDE
#define STEREO_LEFTCOLORFILTER1_APP_PROFILE_ENUM  EN_NONE


#define STEREO_LINECODECOLOR_PREFIX            "_"
#define STEREO_LINECODECOLOR_STRING            ""
#define STEREO_LINECODECOLOR_ID                0x70dc4a12
#define STEREO_LINECODECOLOR_STRING_PLAIN      "STEREO_LINECODECOLOR"
#define STEREO_LINECODECOLOR_OVERINSTALL       0 // OVERRIDE
#define STEREO_LINECODECOLOR_APP_PROFILE_ENUM  EN_NONE


#define STEREO_LINK0_PREFIX            "_"
#define STEREO_LINK0_STRING            ""
#define STEREO_LINK0_ID                0x70a6b72b
#define STEREO_LINK0_STRING_PLAIN      "STEREO_LINK0"
#define STEREO_LINK0_OVERINSTALL       0 // OVERRIDE
#define STEREO_LINK0_APP_PROFILE_ENUM  EN_NONE


#define STEREO_MAXMONITORSIZE_PREFIX            "_"
#define STEREO_MAXMONITORSIZE_STRING            ""
#define STEREO_MAXMONITORSIZE_ID                0x7032022c
#define STEREO_MAXMONITORSIZE_STRING_PLAIN      "STEREO_MAXMONITORSIZE"
#define STEREO_MAXMONITORSIZE_OVERINSTALL       0 // OVERRIDE
#define STEREO_MAXMONITORSIZE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_MAXVERTEXCOUNT_PREFIX            "_"
#define STEREO_MAXVERTEXCOUNT_STRING            ""
#define STEREO_MAXVERTEXCOUNT_ID                0x709e4a94
#define STEREO_MAXVERTEXCOUNT_STRING_PLAIN      "STEREO_MAXVERTEXCOUNT"
#define STEREO_MAXVERTEXCOUNT_OVERINSTALL       0 // OVERRIDE
#define STEREO_MAXVERTEXCOUNT_APP_PROFILE_ENUM  EN_NONE


#define STEREO_MEDIAPLAYER_PREFIX            "_"
#define STEREO_MEDIAPLAYER_STRING            ""
#define STEREO_MEDIAPLAYER_ID                0x70a8fc7f
#define STEREO_MEDIAPLAYER_STRING_PLAIN      "STEREO_MEDIAPLAYER"
#define STEREO_MEDIAPLAYER_OVERINSTALL       0 // OVERRIDE
#define STEREO_MEDIAPLAYER_APP_PROFILE_ENUM  EN_NONE


#define STEREO_MIXEDTNL_PREFIX            "_"
#define STEREO_MIXEDTNL_STRING            ""
#define STEREO_MIXEDTNL_ID                0x70bd11e0
#define STEREO_MIXEDTNL_STRING_PLAIN      "STEREO_MIXEDTNL"
#define STEREO_MIXEDTNL_OVERINSTALL       0 // OVERRIDE
#define STEREO_MIXEDTNL_APP_PROFILE_ENUM  EN_NONE


#define STEREO_MODESETWARNING_PREFIX            "_"
#define STEREO_MODESETWARNING_STRING            ""
#define STEREO_MODESETWARNING_ID                0x70969bb0
#define STEREO_MODESETWARNING_STRING_PLAIN      "STEREO_MODESETWARNING"
#define STEREO_MODESETWARNING_OVERINSTALL       0 // OVERRIDE
#define STEREO_MODESETWARNING_APP_PROFILE_ENUM  EN_NONE


#define STEREO_MONITORSIZE_PREFIX            "_"
#define STEREO_MONITORSIZE_STRING            ""
#define STEREO_MONITORSIZE_ID                0x7086ebe9
#define STEREO_MONITORSIZE_STRING_PLAIN      "STEREO_MONITORSIZE"
#define STEREO_MONITORSIZE_OVERINSTALL       0 // OVERRIDE
#define STEREO_MONITORSIZE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_NOLOCKSUBSTITUTE_PREFIX            "_"
#define STEREO_NOLOCKSUBSTITUTE_STRING            ""
#define STEREO_NOLOCKSUBSTITUTE_ID                0x7005ad16
#define STEREO_NOLOCKSUBSTITUTE_STRING_PLAIN      "STEREO_NOLOCKSUBSTITUTE"
#define STEREO_NOLOCKSUBSTITUTE_OVERINSTALL       0 // OVERRIDE
#define STEREO_NOLOCKSUBSTITUTE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_OCULUS_HT_POSITION_SENSITIVITY_PREFIX            "_"
#define STEREO_OCULUS_HT_POSITION_SENSITIVITY_STRING            ""
#define STEREO_OCULUS_HT_POSITION_SENSITIVITY_ID                0x70d76b90
#define STEREO_OCULUS_HT_POSITION_SENSITIVITY_STRING_PLAIN      "STEREO_OCULUS_HT_POSITION_SENSITIVITY"
#define STEREO_OCULUS_HT_POSITION_SENSITIVITY_OVERINSTALL       0 // OVERRIDE
#define STEREO_OCULUS_HT_POSITION_SENSITIVITY_APP_PROFILE_ENUM  EN_NONE


#define STEREO_OCULUS_HT_SENSITIVITY_PREFIX            "_"
#define STEREO_OCULUS_HT_SENSITIVITY_STRING            ""
#define STEREO_OCULUS_HT_SENSITIVITY_ID                0x70d76b8f
#define STEREO_OCULUS_HT_SENSITIVITY_STRING_PLAIN      "STEREO_OCULUS_HT_SENSITIVITY"
#define STEREO_OCULUS_HT_SENSITIVITY_OVERINSTALL       0 // OVERRIDE
#define STEREO_OCULUS_HT_SENSITIVITY_APP_PROFILE_ENUM  EN_NONE


#define STEREO_OCULUS_SCALE_PREFIX            "_"
#define STEREO_OCULUS_SCALE_STRING            ""
#define STEREO_OCULUS_SCALE_ID                0x70d76b8e
#define STEREO_OCULUS_SCALE_STRING_PLAIN      "STEREO_OCULUS_SCALE"
#define STEREO_OCULUS_SCALE_OVERINSTALL       0 // OVERRIDE
#define STEREO_OCULUS_SCALE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_OCULUS_SETTINGS_PREFIX            "_"
#define STEREO_OCULUS_SETTINGS_STRING            ""
#define STEREO_OCULUS_SETTINGS_ID                0x70d76b8d
#define STEREO_OCULUS_SETTINGS_STRING_PLAIN      "STEREO_OCULUS_SETTINGS"
#define STEREO_OCULUS_SETTINGS_OVERINSTALL       0 // OVERRIDE
#define STEREO_OCULUS_SETTINGS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_OPENGL_PREFIX            "_"
#define STEREO_OPENGL_STRING            ""
#define STEREO_OPENGL_ID                0x7078791d
#define STEREO_OPENGL_STRING_PLAIN      "STEREO_OPENGL"
#define STEREO_OPENGL_OVERINSTALL       0 // OVERRIDE
#define STEREO_OPENGL_APP_PROFILE_ENUM  EN_NONE


#define STEREO_P1SH0_PREFIX            "_"
#define STEREO_P1SH0_STRING            ""
#define STEREO_P1SH0_ID                0x70998683
#define STEREO_P1SH0_STRING_PLAIN      "STEREO_P1SH0"
#define STEREO_P1SH0_OVERINSTALL       0 // OVERRIDE
#define STEREO_P1SH0_APP_PROFILE_ENUM  EN_NONE


#define STEREO_PARTIALCLEARMODE_PREFIX            "_"
#define STEREO_PARTIALCLEARMODE_STRING            ""
#define STEREO_PARTIALCLEARMODE_ID                0x709794cc
#define STEREO_PARTIALCLEARMODE_STRING_PLAIN      "STEREO_PARTIALCLEARMODE"
#define STEREO_PARTIALCLEARMODE_OVERINSTALL       0 // OVERRIDE
#define STEREO_PARTIALCLEARMODE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_PREF_PREFIX            "_"
#define STEREO_PREF_STRING            ""
#define STEREO_PREF_ID                0x702881b8
#define STEREO_PREF_STRING_PLAIN      "STEREO_PREF"
#define STEREO_PREF_OVERINSTALL       0 // OVERRIDE
#define STEREO_PREF_APP_PROFILE_ENUM  EN_NONE


#define STEREO_PSH0_PREFIX            "_"
#define STEREO_PSH0_STRING            ""
#define STEREO_PSH0_ID                0x7046516e
#define STEREO_PSH0_STRING_PLAIN      "STEREO_PSH0"
#define STEREO_PSH0_OVERINSTALL       0 // OVERRIDE
#define STEREO_PSH0_APP_PROFILE_ENUM  EN_NONE


#define STEREO_PUBLISHER_PREFIX            "_"
#define STEREO_PUBLISHER_STRING            ""
#define STEREO_PUBLISHER_ID                0x706c7030
#define STEREO_PUBLISHER_STRING_PLAIN      "STEREO_PUBLISHER"
#define STEREO_PUBLISHER_OVERINSTALL       0 // OVERRIDE
#define STEREO_PUBLISHER_APP_PROFILE_ENUM  EN_NONE


#define STEREO_PUSHBUFSUBSTITUTESIZE_PREFIX            "_"
#define STEREO_PUSHBUFSUBSTITUTESIZE_STRING            ""
#define STEREO_PUSHBUFSUBSTITUTESIZE_ID                0x7054fbf8
#define STEREO_PUSHBUFSUBSTITUTESIZE_STRING_PLAIN      "STEREO_PUSHBUFSUBSTITUTESIZE"
#define STEREO_PUSHBUFSUBSTITUTESIZE_OVERINSTALL       0 // OVERRIDE
#define STEREO_PUSHBUFSUBSTITUTESIZE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_R_PREFIX            "_"
#define STEREO_R_STRING            ""
#define STEREO_R_ID                0x7042966b
#define STEREO_R_STRING_PLAIN      "STEREO_R"
#define STEREO_R_OVERINSTALL       0 // OVERRIDE
#define STEREO_R_APP_PROFILE_ENUM  EN_NONE


#define STEREO_RHW2DDETECTIONMIN_PREFIX            "_"
#define STEREO_RHW2DDETECTIONMIN_STRING            ""
#define STEREO_RHW2DDETECTIONMIN_ID                0x7029432b
#define STEREO_RHW2DDETECTIONMIN_STRING_PLAIN      "STEREO_RHW2DDETECTIONMIN"
#define STEREO_RHW2DDETECTIONMIN_OVERINSTALL       0 // OVERRIDE
#define STEREO_RHW2DDETECTIONMIN_APP_PROFILE_ENUM  EN_NONE


#define STEREO_RHWATSCREENLESS_PREFIX            "_"
#define STEREO_RHWATSCREENLESS_STRING            ""
#define STEREO_RHWATSCREENLESS_ID                0x709139ad
#define STEREO_RHWATSCREENLESS_STRING_PLAIN      "STEREO_RHWATSCREENLESS"
#define STEREO_RHWATSCREENLESS_OVERINSTALL       0 // OVERRIDE
#define STEREO_RHWATSCREENLESS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_RHWATSCREENMORE_PREFIX            "_"
#define STEREO_RHWATSCREENMORE_STRING            ""
#define STEREO_RHWATSCREENMORE_ID                0x7066a22e
#define STEREO_RHWATSCREENMORE_STRING_PLAIN      "STEREO_RHWATSCREENMORE"
#define STEREO_RHWATSCREENMORE_OVERINSTALL       0 // OVERRIDE
#define STEREO_RHWATSCREENMORE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_RHWEQUALATSCREEN_PREFIX            "_"
#define STEREO_RHWEQUALATSCREEN_STRING            ""
#define STEREO_RHWEQUALATSCREEN_ID                0x70ab2e09
#define STEREO_RHWEQUALATSCREEN_STRING_PLAIN      "STEREO_RHWEQUALATSCREEN"
#define STEREO_RHWEQUALATSCREEN_OVERINSTALL       0 // OVERRIDE
#define STEREO_RHWEQUALATSCREEN_APP_PROFILE_ENUM  EN_NONE


#define STEREO_RHWGREATERATSCREEN_PREFIX            "_"
#define STEREO_RHWGREATERATSCREEN_STRING            ""
#define STEREO_RHWGREATERATSCREEN_ID                0x702c861a
#define STEREO_RHWGREATERATSCREEN_STRING_PLAIN      "STEREO_RHWGREATERATSCREEN"
#define STEREO_RHWGREATERATSCREEN_OVERINSTALL       0 // OVERRIDE
#define STEREO_RHWGREATERATSCREEN_APP_PROFILE_ENUM  EN_NONE


#define STEREO_RHWINF_PREFIX            "_"
#define STEREO_RHWINF_STRING            ""
#define STEREO_RHWINF_ID                0x706e1913
#define STEREO_RHWINF_STRING_PLAIN      "STEREO_RHWINF"
#define STEREO_RHWINF_OVERINSTALL       0 // OVERRIDE
#define STEREO_RHWINF_APP_PROFILE_ENUM  EN_NONE


#define STEREO_RHWINF_DX10_PREFIX            "_"
#define STEREO_RHWINF_DX10_STRING            ""
#define STEREO_RHWINF_DX10_ID                0x70cc286a
#define STEREO_RHWINF_DX10_STRING_PLAIN      "STEREO_RHWINF_DX10"
#define STEREO_RHWINF_DX10_OVERINSTALL       0 // OVERRIDE
#define STEREO_RHWINF_DX10_APP_PROFILE_ENUM  EN_NONE


#define STEREO_RHWINF_DX11_PREFIX            "_"
#define STEREO_RHWINF_DX11_STRING            ""
#define STEREO_RHWINF_DX11_ID                0x70a3fee6
#define STEREO_RHWINF_DX11_STRING_PLAIN      "STEREO_RHWINF_DX11"
#define STEREO_RHWINF_DX11_OVERINSTALL       0 // OVERRIDE
#define STEREO_RHWINF_DX11_APP_PROFILE_ENUM  EN_NONE


#define STEREO_RHWLESSATSCREEN_PREFIX            "_"
#define STEREO_RHWLESSATSCREEN_STRING            ""
#define STEREO_RHWLESSATSCREEN_ID                0x70381472
#define STEREO_RHWLESSATSCREEN_STRING_PLAIN      "STEREO_RHWLESSATSCREEN"
#define STEREO_RHWLESSATSCREEN_OVERINSTALL       0 // OVERRIDE
#define STEREO_RHWLESSATSCREEN_APP_PROFILE_ENUM  EN_NONE


#define STEREO_RHWLESSATSCREENLESS_PREFIX            "_"
#define STEREO_RHWLESSATSCREENLESS_STRING            ""
#define STEREO_RHWLESSATSCREENLESS_ID                0x70b378a1
#define STEREO_RHWLESSATSCREENLESS_STRING_PLAIN      "STEREO_RHWLESSATSCREENLESS"
#define STEREO_RHWLESSATSCREENLESS_OVERINSTALL       0 // OVERRIDE
#define STEREO_RHWLESSATSCREENLESS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_RHWLESSATSCREENMORE_PREFIX            "_"
#define STEREO_RHWLESSATSCREENMORE_STRING            ""
#define STEREO_RHWLESSATSCREENMORE_ID                0x704e4bca
#define STEREO_RHWLESSATSCREENMORE_STRING_PLAIN      "STEREO_RHWLESSATSCREENMORE"
#define STEREO_RHWLESSATSCREENMORE_OVERINSTALL       0 // OVERRIDE
#define STEREO_RHWLESSATSCREENMORE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_RHWSCR_PREFIX            "_"
#define STEREO_RHWSCR_STRING            ""
#define STEREO_RHWSCR_ID                0x70a4995c
#define STEREO_RHWSCR_STRING_PLAIN      "STEREO_RHWSCR"
#define STEREO_RHWSCR_OVERINSTALL       0 // OVERRIDE
#define STEREO_RHWSCR_APP_PROFILE_ENUM  EN_NONE


#define STEREO_RHWSCR_DX10_PREFIX            "_"
#define STEREO_RHWSCR_DX10_STRING            ""
#define STEREO_RHWSCR_DX10_ID                0x7030b071
#define STEREO_RHWSCR_DX10_STRING_PLAIN      "STEREO_RHWSCR_DX10"
#define STEREO_RHWSCR_DX10_OVERINSTALL       0 // OVERRIDE
#define STEREO_RHWSCR_DX10_APP_PROFILE_ENUM  EN_NONE


#define STEREO_RHWSCR_DX11_PREFIX            "_"
#define STEREO_RHWSCR_DX11_STRING            ""
#define STEREO_RHWSCR_DX11_ID                0x70b57ed1
#define STEREO_RHWSCR_DX11_STRING_PLAIN      "STEREO_RHWSCR_DX11"
#define STEREO_RHWSCR_DX11_OVERINSTALL       0 // OVERRIDE
#define STEREO_RHWSCR_DX11_APP_PROFILE_ENUM  EN_NONE


#define STEREO_RIGHTANAGLYPHFILTER_PREFIX            "_"
#define STEREO_RIGHTANAGLYPHFILTER_STRING            ""
#define STEREO_RIGHTANAGLYPHFILTER_ID                0x70f4a930
#define STEREO_RIGHTANAGLYPHFILTER_STRING_PLAIN      "STEREO_RIGHTANAGLYPHFILTER"
#define STEREO_RIGHTANAGLYPHFILTER_OVERINSTALL       0 // OVERRIDE
#define STEREO_RIGHTANAGLYPHFILTER_APP_PROFILE_ENUM  EN_NONE


#define STEREO_RIGHTCOLORFILTER0_PREFIX            "_"
#define STEREO_RIGHTCOLORFILTER0_STRING            ""
#define STEREO_RIGHTCOLORFILTER0_ID                0x70b9a2f7
#define STEREO_RIGHTCOLORFILTER0_STRING_PLAIN      "STEREO_RIGHTCOLORFILTER0"
#define STEREO_RIGHTCOLORFILTER0_OVERINSTALL       0 // OVERRIDE
#define STEREO_RIGHTCOLORFILTER0_APP_PROFILE_ENUM  EN_NONE


#define STEREO_RIGHTCOLORFILTER1_PREFIX            "_"
#define STEREO_RIGHTCOLORFILTER1_STRING            ""
#define STEREO_RIGHTCOLORFILTER1_ID                0x70aca0cc
#define STEREO_RIGHTCOLORFILTER1_STRING_PLAIN      "STEREO_RIGHTCOLORFILTER1"
#define STEREO_RIGHTCOLORFILTER1_OVERINSTALL       0 // OVERRIDE
#define STEREO_RIGHTCOLORFILTER1_APP_PROFILE_ENUM  EN_NONE


#define STEREO_RUNTIMENAME_PREFIX            "_"
#define STEREO_RUNTIMENAME_STRING            ""
#define STEREO_RUNTIMENAME_ID                0x701a8be4
#define STEREO_RUNTIMENAME_STRING_PLAIN      "STEREO_RUNTIMENAME"
#define STEREO_RUNTIMENAME_OVERINSTALL       0 // OVERRIDE
#define STEREO_RUNTIMENAME_APP_PROFILE_ENUM  EN_NONE


#define STEREO_R_EXE_NAME_PREFIX            "_"
#define STEREO_R_EXE_NAME_STRING            ""
#define STEREO_R_EXE_NAME_ID                0x70da197a
#define STEREO_R_EXE_NAME_STRING_PLAIN      "STEREO_R_EXE_NAME"
#define STEREO_R_EXE_NAME_OVERINSTALL       0 // OVERRIDE
#define STEREO_R_EXE_NAME_APP_PROFILE_ENUM  EN_NONE


#define STEREO_SAVESTEREOIMAGE_PREFIX            "_"
#define STEREO_SAVESTEREOIMAGE_STRING            ""
#define STEREO_SAVESTEREOIMAGE_ID                0x70121853
#define STEREO_SAVESTEREOIMAGE_STRING_PLAIN      "STEREO_SAVESTEREOIMAGE"
#define STEREO_SAVESTEREOIMAGE_OVERINSTALL       0 // OVERRIDE
#define STEREO_SAVESTEREOIMAGE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_SHARPVPI_PREFIX            "_"
#define STEREO_SHARPVPI_STRING            ""
#define STEREO_SHARPVPI_ID                0x706e0041
#define STEREO_SHARPVPI_STRING_PLAIN      "STEREO_SHARPVPI"
#define STEREO_SHARPVPI_OVERINSTALL       0 // OVERRIDE
#define STEREO_SHARPVPI_APP_PROFILE_ENUM  EN_NONE


#define STEREO_SHOWALLVIEWERTYPES_PREFIX            "_"
#define STEREO_SHOWALLVIEWERTYPES_STRING            ""
#define STEREO_SHOWALLVIEWERTYPES_ID                0x708e5cb4
#define STEREO_SHOWALLVIEWERTYPES_STRING_PLAIN      "STEREO_SHOWALLVIEWERTYPES"
#define STEREO_SHOWALLVIEWERTYPES_OVERINSTALL       0 // OVERRIDE
#define STEREO_SHOWALLVIEWERTYPES_APP_PROFILE_ENUM  EN_NONE


#define STEREO_SNAPSHOTQUALITY_PREFIX            "_"
#define STEREO_SNAPSHOTQUALITY_STRING            ""
#define STEREO_SNAPSHOTQUALITY_ID                0x7004e7a6
#define STEREO_SNAPSHOTQUALITY_STRING_PLAIN      "STEREO_SNAPSHOTQUALITY"
#define STEREO_SNAPSHOTQUALITY_OVERINSTALL       0 // OVERRIDE
#define STEREO_SNAPSHOTQUALITY_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STARTZBIT_PREFIX            "_"
#define STEREO_STARTZBIT_STRING            ""
#define STEREO_STARTZBIT_ID                0x7044d7a6
#define STEREO_STARTZBIT_STRING_PLAIN      "STEREO_STARTZBIT"
#define STEREO_STARTZBIT_OVERINSTALL       0 // OVERRIDE
#define STEREO_STARTZBIT_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOADJUSTENABLE_PREFIX            "_"
#define STEREO_STEREOADJUSTENABLE_STRING            ""
#define STEREO_STEREOADJUSTENABLE_ID                0x70538ab1
#define STEREO_STEREOADJUSTENABLE_STRING_PLAIN      "STEREO_STEREOADJUSTENABLE"
#define STEREO_STEREOADJUSTENABLE_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOADJUSTENABLE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOCOLORKEY_PREFIX            "_"
#define STEREO_STEREOCOLORKEY_STRING            ""
#define STEREO_STEREOCOLORKEY_ID                0x70e5773b
#define STEREO_STEREOCOLORKEY_STRING_PLAIN      "STEREO_STEREOCOLORKEY"
#define STEREO_STEREOCOLORKEY_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOCOLORKEY_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOCOMPATIBILITY_PREFIX            "_"
#define STEREO_STEREOCOMPATIBILITY_STRING            ""
#define STEREO_STEREOCOMPATIBILITY_ID                0x70a2000e
#define STEREO_STEREOCOMPATIBILITY_STRING_PLAIN      "STEREO_STEREOCOMPATIBILITY"
#define STEREO_STEREOCOMPATIBILITY_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOCOMPATIBILITY_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOCONVERGENCE_PREFIX            "_"
#define STEREO_STEREOCONVERGENCE_STRING            ""
#define STEREO_STEREOCONVERGENCE_ID                0x708db8c5
#define STEREO_STEREOCONVERGENCE_STRING_PLAIN      "STEREO_STEREOCONVERGENCE"
#define STEREO_STEREOCONVERGENCE_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOCONVERGENCE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOCONVERGENCEADJUSTLESS_PREFIX            "_"
#define STEREO_STEREOCONVERGENCEADJUSTLESS_STRING            ""
#define STEREO_STEREOCONVERGENCEADJUSTLESS_ID                0x70d4add7
#define STEREO_STEREOCONVERGENCEADJUSTLESS_STRING_PLAIN      "STEREO_STEREOCONVERGENCEADJUSTLESS"
#define STEREO_STEREOCONVERGENCEADJUSTLESS_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOCONVERGENCEADJUSTLESS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOCONVERGENCEADJUSTMORE_PREFIX            "_"
#define STEREO_STEREOCONVERGENCEADJUSTMORE_STRING            ""
#define STEREO_STEREOCONVERGENCEADJUSTMORE_ID                0x701ed576
#define STEREO_STEREOCONVERGENCEADJUSTMORE_STRING_PLAIN      "STEREO_STEREOCONVERGENCEADJUSTMORE"
#define STEREO_STEREOCONVERGENCEADJUSTMORE_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOCONVERGENCEADJUSTMORE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOCONVERGENCEMULTIPLIER_PREFIX            "_"
#define STEREO_STEREOCONVERGENCEMULTIPLIER_STRING            ""
#define STEREO_STEREOCONVERGENCEMULTIPLIER_ID                0x70efbb5b
#define STEREO_STEREOCONVERGENCEMULTIPLIER_STRING_PLAIN      "STEREO_STEREOCONVERGENCEMULTIPLIER"
#define STEREO_STEREOCONVERGENCEMULTIPLIER_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOCONVERGENCEMULTIPLIER_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOCONVERGENCE_DX10_PREFIX            "_"
#define STEREO_STEREOCONVERGENCE_DX10_STRING            ""
#define STEREO_STEREOCONVERGENCE_DX10_ID                0x7077bace
#define STEREO_STEREOCONVERGENCE_DX10_STRING_PLAIN      "STEREO_STEREOCONVERGENCE_DX10"
#define STEREO_STEREOCONVERGENCE_DX10_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOCONVERGENCE_DX10_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOCONVERGENCE_DX11_PREFIX            "_"
#define STEREO_STEREOCONVERGENCE_DX11_STRING            ""
#define STEREO_STEREOCONVERGENCE_DX11_ID                0x7084807e
#define STEREO_STEREOCONVERGENCE_DX11_STRING_PLAIN      "STEREO_STEREOCONVERGENCE_DX11"
#define STEREO_STEREOCONVERGENCE_DX11_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOCONVERGENCE_DX11_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOCUTOFF_PREFIX            "_"
#define STEREO_STEREOCUTOFF_STRING            ""
#define STEREO_STEREOCUTOFF_ID                0x709a1ddf
#define STEREO_STEREOCUTOFF_STRING_PLAIN      "STEREO_STEREOCUTOFF"
#define STEREO_STEREOCUTOFF_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOCUTOFF_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOCUTOFFDEPTHFAR_PREFIX            "_"
#define STEREO_STEREOCUTOFFDEPTHFAR_STRING            ""
#define STEREO_STEREOCUTOFFDEPTHFAR_ID                0x70add220
#define STEREO_STEREOCUTOFFDEPTHFAR_STRING_PLAIN      "STEREO_STEREOCUTOFFDEPTHFAR"
#define STEREO_STEREOCUTOFFDEPTHFAR_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOCUTOFFDEPTHFAR_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOCUTOFFDEPTHNEAR_PREFIX            "_"
#define STEREO_STEREOCUTOFFDEPTHNEAR_STRING            ""
#define STEREO_STEREOCUTOFFDEPTHNEAR_ID                0x7050e011
#define STEREO_STEREOCUTOFFDEPTHNEAR_STRING_PLAIN      "STEREO_STEREOCUTOFFDEPTHNEAR"
#define STEREO_STEREOCUTOFFDEPTHNEAR_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOCUTOFFDEPTHNEAR_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOCUTOFFDEPTHNEAR_DX10_PREFIX            "_"
#define STEREO_STEREOCUTOFFDEPTHNEAR_DX10_STRING            ""
#define STEREO_STEREOCUTOFFDEPTHNEAR_DX10_ID                0x704ef483
#define STEREO_STEREOCUTOFFDEPTHNEAR_DX10_STRING_PLAIN      "STEREO_STEREOCUTOFFDEPTHNEAR_DX10"
#define STEREO_STEREOCUTOFFDEPTHNEAR_DX10_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOCUTOFFDEPTHNEAR_DX10_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOCUTOFFDEPTHNEAR_DX11_PREFIX            "_"
#define STEREO_STEREOCUTOFFDEPTHNEAR_DX11_STRING            ""
#define STEREO_STEREOCUTOFFDEPTHNEAR_DX11_ID                0x7031de06
#define STEREO_STEREOCUTOFFDEPTHNEAR_DX11_STRING_PLAIN      "STEREO_STEREOCUTOFFDEPTHNEAR_DX11"
#define STEREO_STEREOCUTOFFDEPTHNEAR_DX11_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOCUTOFFDEPTHNEAR_DX11_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOCUTOFF_DX10_PREFIX            "_"
#define STEREO_STEREOCUTOFF_DX10_STRING            ""
#define STEREO_STEREOCUTOFF_DX10_ID                0x704fcf5c
#define STEREO_STEREOCUTOFF_DX10_STRING_PLAIN      "STEREO_STEREOCUTOFF_DX10"
#define STEREO_STEREOCUTOFF_DX10_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOCUTOFF_DX10_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOCUTOFF_DX11_PREFIX            "_"
#define STEREO_STEREOCUTOFF_DX11_STRING            ""
#define STEREO_STEREOCUTOFF_DX11_ID                0x7053569a
#define STEREO_STEREOCUTOFF_DX11_STRING_PLAIN      "STEREO_STEREOCUTOFF_DX11"
#define STEREO_STEREOCUTOFF_DX11_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOCUTOFF_DX11_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREODEFAULTON_PREFIX            "_"
#define STEREO_STEREODEFAULTON_STRING            ""
#define STEREO_STEREODEFAULTON_ID                0x70ab30a7
#define STEREO_STEREODEFAULTON_STRING_PLAIN      "STEREO_STEREODEFAULTON"
#define STEREO_STEREODEFAULTON_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREODEFAULTON_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREODISABLEASYNC_PREFIX            "_"
#define STEREO_STEREODISABLEASYNC_STRING            ""
#define STEREO_STEREODISABLEASYNC_ID                0x70de5533
#define STEREO_STEREODISABLEASYNC_STRING_PLAIN      "STEREO_STEREODISABLEASYNC"
#define STEREO_STEREODISABLEASYNC_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREODISABLEASYNC_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREODISABLETNL_PREFIX            "_"
#define STEREO_STEREODISABLETNL_STRING            ""
#define STEREO_STEREODISABLETNL_ID                0x70633bd9
#define STEREO_STEREODISABLETNL_STRING_PLAIN      "STEREO_STEREODISABLETNL"
#define STEREO_STEREODISABLETNL_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREODISABLETNL_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREODX9_PREFIX            "_"
#define STEREO_STEREODX9_STRING            ""
#define STEREO_STEREODX9_ID                0x70d10d2b
#define STEREO_STEREODX9_STRING_PLAIN      "STEREO_STEREODX9"
#define STEREO_STEREODX9_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREODX9_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOEASYZCHECK_PREFIX            "_"
#define STEREO_STEREOEASYZCHECK_STRING            ""
#define STEREO_STEREOEASYZCHECK_ID                0x70b6d6ed
#define STEREO_STEREOEASYZCHECK_STRING_PLAIN      "STEREO_STEREOEASYZCHECK"
#define STEREO_STEREOEASYZCHECK_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOEASYZCHECK_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOENABLESTEREOCURSOR_PREFIX            "_"
#define STEREO_STEREOENABLESTEREOCURSOR_STRING            ""
#define STEREO_STEREOENABLESTEREOCURSOR_ID                0x70e46f2b
#define STEREO_STEREOENABLESTEREOCURSOR_STRING_PLAIN      "STEREO_STEREOENABLESTEREOCURSOR"
#define STEREO_STEREOENABLESTEREOCURSOR_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOENABLESTEREOCURSOR_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOEPSILON_PREFIX            "_"
#define STEREO_STEREOEPSILON_STRING            ""
#define STEREO_STEREOEPSILON_ID                0x70e5a749
#define STEREO_STEREOEPSILON_STRING_PLAIN      "STEREO_STEREOEPSILON"
#define STEREO_STEREOEPSILON_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOEPSILON_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOFIRSTTIME_PREFIX            "_"
#define STEREO_STEREOFIRSTTIME_STRING            ""
#define STEREO_STEREOFIRSTTIME_ID                0x70af6400
#define STEREO_STEREOFIRSTTIME_STRING_PLAIN      "STEREO_STEREOFIRSTTIME"
#define STEREO_STEREOFIRSTTIME_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOFIRSTTIME_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOFLAGSDX10_PREFIX            "_"
#define STEREO_STEREOFLAGSDX10_STRING            ""
#define STEREO_STEREOFLAGSDX10_ID                0x702442fc
#define STEREO_STEREOFLAGSDX10_STRING_PLAIN      "STEREO_STEREOFLAGSDX10"
#define STEREO_STEREOFLAGSDX10_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOFLAGSDX10_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOFORCEVSYNC_PREFIX            "_"
#define STEREO_STEREOFORCEVSYNC_STRING            ""
#define STEREO_STEREOFORCEVSYNC_ID                0x70aae185
#define STEREO_STEREOFORCEVSYNC_STRING_PLAIN      "STEREO_STEREOFORCEVSYNC"
#define STEREO_STEREOFORCEVSYNC_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOFORCEVSYNC_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOGAMMA_PREFIX            "_"
#define STEREO_STEREOGAMMA_STRING            ""
#define STEREO_STEREOGAMMA_ID                0x70c8b5d1
#define STEREO_STEREOGAMMA_STRING_PLAIN      "STEREO_STEREOGAMMA"
#define STEREO_STEREOGAMMA_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOGAMMA_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOHIDDENPROFILE_PREFIX            "_"
#define STEREO_STEREOHIDDENPROFILE_STRING            ""
#define STEREO_STEREOHIDDENPROFILE_ID                0x70e46f20
#define STEREO_STEREOHIDDENPROFILE_STRING_PLAIN      "STEREO_STEREOHIDDENPROFILE"
#define STEREO_STEREOHIDDENPROFILE_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOHIDDENPROFILE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOHORIZONTALADJUSTLESS_PREFIX            "_"
#define STEREO_STEREOHORIZONTALADJUSTLESS_STRING            ""
#define STEREO_STEREOHORIZONTALADJUSTLESS_ID                0x70871a39
#define STEREO_STEREOHORIZONTALADJUSTLESS_STRING_PLAIN      "STEREO_STEREOHORIZONTALADJUSTLESS"
#define STEREO_STEREOHORIZONTALADJUSTLESS_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOHORIZONTALADJUSTLESS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOHORIZONTALADJUSTMORE_PREFIX            "_"
#define STEREO_STEREOHORIZONTALADJUSTMORE_STRING            ""
#define STEREO_STEREOHORIZONTALADJUSTMORE_ID                0x70062f07
#define STEREO_STEREOHORIZONTALADJUSTMORE_STRING_PLAIN      "STEREO_STEREOHORIZONTALADJUSTMORE"
#define STEREO_STEREOHORIZONTALADJUSTMORE_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOHORIZONTALADJUSTMORE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOIMAGETYPE_PREFIX            "_"
#define STEREO_STEREOIMAGETYPE_STRING            ""
#define STEREO_STEREOIMAGETYPE_ID                0x7097906c
#define STEREO_STEREOIMAGETYPE_STRING_PLAIN      "STEREO_STEREOIMAGETYPE"
#define STEREO_STEREOIMAGETYPE_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOIMAGETYPE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOLASERSIGHTCOUNT_PREFIX            "_"
#define STEREO_STEREOLASERSIGHTCOUNT_STRING            ""
#define STEREO_STEREOLASERSIGHTCOUNT_ID                0x70077042
#define STEREO_STEREOLASERSIGHTCOUNT_STRING_PLAIN      "STEREO_STEREOLASERSIGHTCOUNT"
#define STEREO_STEREOLASERSIGHTCOUNT_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOLASERSIGHTCOUNT_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOLASERSIGHTMAXCOUNT_PREFIX            "_"
#define STEREO_STEREOLASERSIGHTMAXCOUNT_STRING            ""
#define STEREO_STEREOLASERSIGHTMAXCOUNT_ID                0x70bc864d
#define STEREO_STEREOLASERSIGHTMAXCOUNT_STRING_PLAIN      "STEREO_STEREOLASERSIGHTMAXCOUNT"
#define STEREO_STEREOLASERSIGHTMAXCOUNT_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOLASERSIGHTMAXCOUNT_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOLCDPATTERNTYPE_PREFIX            "_"
#define STEREO_STEREOLCDPATTERNTYPE_STRING            ""
#define STEREO_STEREOLCDPATTERNTYPE_ID                0x707cfb97
#define STEREO_STEREOLCDPATTERNTYPE_STRING_PLAIN      "STEREO_STEREOLCDPATTERNTYPE"
#define STEREO_STEREOLCDPATTERNTYPE_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOLCDPATTERNTYPE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOLINKDLL_PREFIX            "_"
#define STEREO_STEREOLINKDLL_STRING            ""
#define STEREO_STEREOLINKDLL_ID                0x70e46f2a
#define STEREO_STEREOLINKDLL_STRING_PLAIN      "STEREO_STEREOLINKDLL"
#define STEREO_STEREOLINKDLL_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOLINKDLL_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOLOGSHADERS_PREFIX            "_"
#define STEREO_STEREOLOGSHADERS_STRING            ""
#define STEREO_STEREOLOGSHADERS_ID                0x7052bdd0
#define STEREO_STEREOLOGSHADERS_STRING_PLAIN      "STEREO_STEREOLOGSHADERS"
#define STEREO_STEREOLOGSHADERS_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOLOGSHADERS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOMEMOENABLED_PREFIX            "_"
#define STEREO_STEREOMEMOENABLED_STRING            ""
#define STEREO_STEREOMEMOENABLED_ID                0x707f4b45
#define STEREO_STEREOMEMOENABLED_STRING_PLAIN      "STEREO_STEREOMEMOENABLED"
#define STEREO_STEREOMEMOENABLED_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOMEMOENABLED_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOMISCFLAGS_PREFIX            "_"
#define STEREO_STEREOMISCFLAGS_STRING            ""
#define STEREO_STEREOMISCFLAGS_ID                0x70ccb5f0
#define STEREO_STEREOMISCFLAGS_STRING_PLAIN      "STEREO_STEREOMISCFLAGS"
#define STEREO_STEREOMISCFLAGS_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOMISCFLAGS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOMODE_PREFIX            "_"
#define STEREO_STEREOMODE_STRING            ""
#define STEREO_STEREOMODE_ID                0x701baa09
#define STEREO_STEREOMODE_STRING_PLAIN      "STEREO_STEREOMODE"
#define STEREO_STEREOMODE_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOMODE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOMSGVERTICALOFFSET_PREFIX            "_"
#define STEREO_STEREOMSGVERTICALOFFSET_STRING            ""
#define STEREO_STEREOMSGVERTICALOFFSET_ID                0x70160ebf
#define STEREO_STEREOMSGVERTICALOFFSET_STRING_PLAIN      "STEREO_STEREOMSGVERTICALOFFSET"
#define STEREO_STEREOMSGVERTICALOFFSET_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOMSGVERTICALOFFSET_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREONODEPTHOVERRIDE_PREFIX            "_"
#define STEREO_STEREONODEPTHOVERRIDE_STRING            ""
#define STEREO_STEREONODEPTHOVERRIDE_ID                0x709dea62
#define STEREO_STEREONODEPTHOVERRIDE_STRING_PLAIN      "STEREO_STEREONODEPTHOVERRIDE"
#define STEREO_STEREONODEPTHOVERRIDE_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREONODEPTHOVERRIDE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREONOTSUPPORTED_PREFIX            "_"
#define STEREO_STEREONOTSUPPORTED_STRING            ""
#define STEREO_STEREONOTSUPPORTED_ID                0x709aa171
#define STEREO_STEREONOTSUPPORTED_STRING_PLAIN      "STEREO_STEREONOTSUPPORTED"
#define STEREO_STEREONOTSUPPORTED_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREONOTSUPPORTED_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOORTHOENABLE_PREFIX            "_"
#define STEREO_STEREOORTHOENABLE_STRING            ""
#define STEREO_STEREOORTHOENABLE_ID                0x703564f6
#define STEREO_STEREOORTHOENABLE_STRING_PLAIN      "STEREO_STEREOORTHOENABLE"
#define STEREO_STEREOORTHOENABLE_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOORTHOENABLE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOOSDENABLE_PREFIX            "_"
#define STEREO_STEREOOSDENABLE_STRING            ""
#define STEREO_STEREOOSDENABLE_ID                0x70f455aa
#define STEREO_STEREOOSDENABLE_STRING_PLAIN      "STEREO_STEREOOSDENABLE"
#define STEREO_STEREOOSDENABLE_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOOSDENABLE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOPOINTER_PREFIX            "_"
#define STEREO_STEREOPOINTER_STRING            ""
#define STEREO_STEREOPOINTER_ID                0x70364596
#define STEREO_STEREOPOINTER_STRING_PLAIN      "STEREO_STEREOPOINTER"
#define STEREO_STEREOPOINTER_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOPOINTER_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOPROFILE_PREFIX            "_"
#define STEREO_STEREOPROFILE_STRING            ""
#define STEREO_STEREOPROFILE_ID                0x701eb457
#define STEREO_STEREOPROFILE_STRING_PLAIN      "STEREO_STEREOPROFILE"
#define STEREO_STEREOPROFILE_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOPROFILE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOREFRESHDEFAULTON_PREFIX            "_"
#define STEREO_STEREOREFRESHDEFAULTON_STRING            ""
#define STEREO_STEREOREFRESHDEFAULTON_ID                0x702ba385
#define STEREO_STEREOREFRESHDEFAULTON_STRING_PLAIN      "STEREO_STEREOREFRESHDEFAULTON"
#define STEREO_STEREOREFRESHDEFAULTON_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOREFRESHDEFAULTON_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOREFRESHRATE_PREFIX            "_"
#define STEREO_STEREOREFRESHRATE_STRING            ""
#define STEREO_STEREOREFRESHRATE_ID                0x70ded3c0
#define STEREO_STEREOREFRESHRATE_STRING_PLAIN      "STEREO_STEREOREFRESHRATE"
#define STEREO_STEREOREFRESHRATE_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOREFRESHRATE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOSEPARATION_PREFIX            "_"
#define STEREO_STEREOSEPARATION_STRING            ""
#define STEREO_STEREOSEPARATION_ID                0x70933c00
#define STEREO_STEREOSEPARATION_STRING_PLAIN      "STEREO_STEREOSEPARATION"
#define STEREO_STEREOSEPARATION_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOSEPARATION_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOSEPARATIONADJUSTLESS_PREFIX            "_"
#define STEREO_STEREOSEPARATIONADJUSTLESS_STRING            ""
#define STEREO_STEREOSEPARATIONADJUSTLESS_ID                0x705d1e02
#define STEREO_STEREOSEPARATIONADJUSTLESS_STRING_PLAIN      "STEREO_STEREOSEPARATIONADJUSTLESS"
#define STEREO_STEREOSEPARATIONADJUSTLESS_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOSEPARATIONADJUSTLESS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOSEPARATIONADJUSTMORE_PREFIX            "_"
#define STEREO_STEREOSEPARATIONADJUSTMORE_STRING            ""
#define STEREO_STEREOSEPARATIONADJUSTMORE_ID                0x70ab8d32
#define STEREO_STEREOSEPARATIONADJUSTMORE_STRING_PLAIN      "STEREO_STEREOSEPARATIONADJUSTMORE"
#define STEREO_STEREOSEPARATIONADJUSTMORE_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOSEPARATIONADJUSTMORE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOSEPARATIONSTEP_PREFIX            "_"
#define STEREO_STEREOSEPARATIONSTEP_STRING            ""
#define STEREO_STEREOSEPARATIONSTEP_ID                0x7082555b
#define STEREO_STEREOSEPARATIONSTEP_STRING_PLAIN      "STEREO_STEREOSEPARATIONSTEP"
#define STEREO_STEREOSEPARATIONSTEP_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOSEPARATIONSTEP_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOSHADERMATRIXCHECK_PREFIX            "_"
#define STEREO_STEREOSHADERMATRIXCHECK_STRING            ""
#define STEREO_STEREOSHADERMATRIXCHECK_ID                0x7044f8fb
#define STEREO_STEREOSHADERMATRIXCHECK_STRING_PLAIN      "STEREO_STEREOSHADERMATRIXCHECK"
#define STEREO_STEREOSHADERMATRIXCHECK_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOSHADERMATRIXCHECK_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOSTRICTLSCHECK_PREFIX            "_"
#define STEREO_STEREOSTRICTLSCHECK_STRING            ""
#define STEREO_STEREOSTRICTLSCHECK_ID                0x709bc378
#define STEREO_STEREOSTRICTLSCHECK_STRING_PLAIN      "STEREO_STEREOSTRICTLSCHECK"
#define STEREO_STEREOSTRICTLSCHECK_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOSTRICTLSCHECK_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOSUGGESTSETTINGS_PREFIX            "_"
#define STEREO_STEREOSUGGESTSETTINGS_STRING            ""
#define STEREO_STEREOSUGGESTSETTINGS_ID                0x706315af
#define STEREO_STEREOSUGGESTSETTINGS_STRING_PLAIN      "STEREO_STEREOSUGGESTSETTINGS"
#define STEREO_STEREOSUGGESTSETTINGS_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOSUGGESTSETTINGS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOTEXTUREENABLE_PREFIX            "_"
#define STEREO_STEREOTEXTUREENABLE_STRING            ""
#define STEREO_STEREOTEXTUREENABLE_ID                0x70edb381
#define STEREO_STEREOTEXTUREENABLE_STRING_PLAIN      "STEREO_STEREOTEXTUREENABLE"
#define STEREO_STEREOTEXTUREENABLE_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOTEXTUREENABLE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOTEXTUREENABLE_DX10_PREFIX            "_"
#define STEREO_STEREOTEXTUREENABLE_DX10_STRING            ""
#define STEREO_STEREOTEXTUREENABLE_DX10_ID                0x70e1518c
#define STEREO_STEREOTEXTUREENABLE_DX10_STRING_PLAIN      "STEREO_STEREOTEXTUREENABLE_DX10"
#define STEREO_STEREOTEXTUREENABLE_DX10_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOTEXTUREENABLE_DX10_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOTEXTUREENABLE_DX11_PREFIX            "_"
#define STEREO_STEREOTEXTUREENABLE_DX11_STRING            ""
#define STEREO_STEREOTEXTUREENABLE_DX11_ID                0x70c0125e
#define STEREO_STEREOTEXTUREENABLE_DX11_STRING_PLAIN      "STEREO_STEREOTEXTUREENABLE_DX11"
#define STEREO_STEREOTEXTUREENABLE_DX11_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOTEXTUREENABLE_DX11_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOTOGGLE_PREFIX            "_"
#define STEREO_STEREOTOGGLE_STRING            ""
#define STEREO_STEREOTOGGLE_ID                0x70d76b8b
#define STEREO_STEREOTOGGLE_STRING_PLAIN      "STEREO_STEREOTOGGLE"
#define STEREO_STEREOTOGGLE_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOTOGGLE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOTRANSFORMATIONTYPE_PREFIX            "_"
#define STEREO_STEREOTRANSFORMATIONTYPE_STRING            ""
#define STEREO_STEREOTRANSFORMATIONTYPE_ID                0x70c27e3c
#define STEREO_STEREOTRANSFORMATIONTYPE_STRING_PLAIN      "STEREO_STEREOTRANSFORMATIONTYPE"
#define STEREO_STEREOTRANSFORMATIONTYPE_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOTRANSFORMATIONTYPE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOUNSUGGESTSETTINGS_PREFIX            "_"
#define STEREO_STEREOUNSUGGESTSETTINGS_STRING            ""
#define STEREO_STEREOUNSUGGESTSETTINGS_ID                0x7017861c
#define STEREO_STEREOUNSUGGESTSETTINGS_STRING_PLAIN      "STEREO_STEREOUNSUGGESTSETTINGS"
#define STEREO_STEREOUNSUGGESTSETTINGS_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOUNSUGGESTSETTINGS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOUSEMATRIX_PREFIX            "_"
#define STEREO_STEREOUSEMATRIX_STRING            ""
#define STEREO_STEREOUSEMATRIX_ID                0x70e34a78
#define STEREO_STEREOUSEMATRIX_STRING_PLAIN      "STEREO_STEREOUSEMATRIX"
#define STEREO_STEREOUSEMATRIX_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOUSEMATRIX_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOVERTICALADJUSTLESS_PREFIX            "_"
#define STEREO_STEREOVERTICALADJUSTLESS_STRING            ""
#define STEREO_STEREOVERTICALADJUSTLESS_ID                0x703acfc6
#define STEREO_STEREOVERTICALADJUSTLESS_STRING_PLAIN      "STEREO_STEREOVERTICALADJUSTLESS"
#define STEREO_STEREOVERTICALADJUSTLESS_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOVERTICALADJUSTLESS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOVERTICALADJUSTMORE_PREFIX            "_"
#define STEREO_STEREOVERTICALADJUSTMORE_STRING            ""
#define STEREO_STEREOVERTICALADJUSTMORE_ID                0x7087fe61
#define STEREO_STEREOVERTICALADJUSTMORE_STRING_PLAIN      "STEREO_STEREOVERTICALADJUSTMORE"
#define STEREO_STEREOVERTICALADJUSTMORE_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOVERTICALADJUSTMORE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOVIEWER_PREFIX            "_"
#define STEREO_STEREOVIEWER_STRING            ""
#define STEREO_STEREOVIEWER_ID                0x704915a1
#define STEREO_STEREOVIEWER_STRING_PLAIN      "STEREO_STEREOVIEWER"
#define STEREO_STEREOVIEWER_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOVIEWER_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOVIEWERTYPE_PREFIX            "_"
#define STEREO_STEREOVIEWERTYPE_STRING            ""
#define STEREO_STEREOVIEWERTYPE_ID                0x708f9ef7
#define STEREO_STEREOVIEWERTYPE_STRING_PLAIN      "STEREO_STEREOVIEWERTYPE"
#define STEREO_STEREOVIEWERTYPE_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOVIEWERTYPE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOVRCONVERGENCEBIAS_PREFIX            "_"
#define STEREO_STEREOVRCONVERGENCEBIAS_STRING            ""
#define STEREO_STEREOVRCONVERGENCEBIAS_ID                0x708db8c6
#define STEREO_STEREOVRCONVERGENCEBIAS_STRING_PLAIN      "STEREO_STEREOVRCONVERGENCEBIAS"
#define STEREO_STEREOVRCONVERGENCEBIAS_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOVRCONVERGENCEBIAS_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOVRCONVERGENCEBIAS_DX10_PREFIX            "_"
#define STEREO_STEREOVRCONVERGENCEBIAS_DX10_STRING            ""
#define STEREO_STEREOVRCONVERGENCEBIAS_DX10_ID                0x7077bacd
#define STEREO_STEREOVRCONVERGENCEBIAS_DX10_STRING_PLAIN      "STEREO_STEREOVRCONVERGENCEBIAS_DX10"
#define STEREO_STEREOVRCONVERGENCEBIAS_DX10_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOVRCONVERGENCEBIAS_DX10_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOVRCONVERGENCEBIAS_DX11_PREFIX            "_"
#define STEREO_STEREOVRCONVERGENCEBIAS_DX11_STRING            ""
#define STEREO_STEREOVRCONVERGENCEBIAS_DX11_ID                0x7084807d
#define STEREO_STEREOVRCONVERGENCEBIAS_DX11_STRING_PLAIN      "STEREO_STEREOVRCONVERGENCEBIAS_DX11"
#define STEREO_STEREOVRCONVERGENCEBIAS_DX11_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOVRCONVERGENCEBIAS_DX11_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOVRREFRESHRATEOVERRIDE_PREFIX            "_"
#define STEREO_STEREOVRREFRESHRATEOVERRIDE_STRING            ""
#define STEREO_STEREOVRREFRESHRATEOVERRIDE_ID                0x708db8c8
#define STEREO_STEREOVRREFRESHRATEOVERRIDE_STRING_PLAIN      "STEREO_STEREOVRREFRESHRATEOVERRIDE"
#define STEREO_STEREOVRREFRESHRATEOVERRIDE_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOVRREFRESHRATEOVERRIDE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STEREOVRVSYNC_PREFIX            "_"
#define STEREO_STEREOVRVSYNC_STRING            ""
#define STEREO_STEREOVRVSYNC_ID                0x708db8c9
#define STEREO_STEREOVRVSYNC_STRING_PLAIN      "STEREO_STEREOVRVSYNC"
#define STEREO_STEREOVRVSYNC_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOVRVSYNC_APP_PROFILE_ENUM  EN_NONE
namespace STEREO_STEREOVRVSYNC_NAMESPACE
{
    enum STEREO_STEREOVRVSYNC_ENUM 
    {
        VR_VSYNC_ON = 0x00000001,
        VR_VSYNC_OFF = 0x00000000,
        VR_VSYNC_GAME_CONTROLLED = 0x00000002
    };
}


#define STEREO_STEREOWINDOWEDENABLE_PREFIX            "_"
#define STEREO_STEREOWINDOWEDENABLE_STRING            ""
#define STEREO_STEREOWINDOWEDENABLE_ID                0x709b3484
#define STEREO_STEREOWINDOWEDENABLE_STRING_PLAIN      "STEREO_STEREOWINDOWEDENABLE"
#define STEREO_STEREOWINDOWEDENABLE_OVERINSTALL       0 // OVERRIDE
#define STEREO_STEREOWINDOWEDENABLE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_STYLE_PREFIX            "_"
#define STEREO_STYLE_STRING            ""
#define STEREO_STYLE_ID                0x709cc5e0
#define STEREO_STYLE_STRING_PLAIN      "STEREO_STYLE"
#define STEREO_STYLE_OVERINSTALL       0 // OVERRIDE
#define STEREO_STYLE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_TIME_PREFIX            "_"
#define STEREO_TIME_STRING            ""
#define STEREO_TIME_ID                0x70ad05c8
#define STEREO_TIME_STRING_PLAIN      "STEREO_TIME"
#define STEREO_TIME_OVERINSTALL       0 // OVERRIDE
#define STEREO_TIME_APP_PROFILE_ENUM  EN_NONE


#define STEREO_TOGGLEAUTOCONVERGENCE_PREFIX            "_"
#define STEREO_TOGGLEAUTOCONVERGENCE_STRING            ""
#define STEREO_TOGGLEAUTOCONVERGENCE_ID                0x70085de3
#define STEREO_TOGGLEAUTOCONVERGENCE_STRING_PLAIN      "STEREO_TOGGLEAUTOCONVERGENCE"
#define STEREO_TOGGLEAUTOCONVERGENCE_OVERINSTALL       0 // OVERRIDE
#define STEREO_TOGGLEAUTOCONVERGENCE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_TOGGLEAUTOCONVERGENCERESTORE_PREFIX            "_"
#define STEREO_TOGGLEAUTOCONVERGENCERESTORE_STRING            ""
#define STEREO_TOGGLEAUTOCONVERGENCERESTORE_ID                0x703bc51e
#define STEREO_TOGGLEAUTOCONVERGENCERESTORE_STRING_PLAIN      "STEREO_TOGGLEAUTOCONVERGENCERESTORE"
#define STEREO_TOGGLEAUTOCONVERGENCERESTORE_OVERINSTALL       0 // OVERRIDE
#define STEREO_TOGGLEAUTOCONVERGENCERESTORE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_TOGGLELASERSIGHT_PREFIX            "_"
#define STEREO_TOGGLELASERSIGHT_STRING            ""
#define STEREO_TOGGLELASERSIGHT_ID                0x70b7bd1f
#define STEREO_TOGGLELASERSIGHT_STRING_PLAIN      "STEREO_TOGGLELASERSIGHT"
#define STEREO_TOGGLELASERSIGHT_OVERINSTALL       0 // OVERRIDE
#define STEREO_TOGGLELASERSIGHT_APP_PROFILE_ENUM  EN_NONE


#define STEREO_TOGGLEMODE_PREFIX            "_"
#define STEREO_TOGGLEMODE_STRING            ""
#define STEREO_TOGGLEMODE_ID                0x70d76b8c
#define STEREO_TOGGLEMODE_STRING_PLAIN      "STEREO_TOGGLEMODE"
#define STEREO_TOGGLEMODE_OVERINSTALL       0 // OVERRIDE
#define STEREO_TOGGLEMODE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_V1SH0_PREFIX            "_"
#define STEREO_V1SH0_STRING            ""
#define STEREO_V1SH0_ID                0x70e6a3cf
#define STEREO_V1SH0_STRING_PLAIN      "STEREO_V1SH0"
#define STEREO_V1SH0_OVERINSTALL       0 // OVERRIDE
#define STEREO_V1SH0_APP_PROFILE_ENUM  EN_NONE


#define STEREO_VALUE_PREFIX            "_"
#define STEREO_VALUE_STRING            ""
#define STEREO_VALUE_ID                0x7049c7ec
#define STEREO_VALUE_STRING_PLAIN      "STEREO_VALUE"
#define STEREO_VALUE_OVERINSTALL       0 // OVERRIDE
#define STEREO_VALUE_APP_PROFILE_ENUM  EN_NONE


#define STEREO_VR_EXCLUSIVITY_FLAGS_PREFIX            "_"
#define STEREO_VR_EXCLUSIVITY_FLAGS_STRING            ""
#define STEREO_VR_EXCLUSIVITY_FLAGS_ID                0x709d3ad2
#define STEREO_VR_EXCLUSIVITY_FLAGS_STRING_PLAIN      "STEREO_VR_EXCLUSIVITY_FLAGS"
#define STEREO_VR_EXCLUSIVITY_FLAGS_OVERINSTALL       0 // OVERRIDE
#define STEREO_VR_EXCLUSIVITY_FLAGS_DEFAULT           STEREO_VR_EXCLUSIVITY_FLAGS_NAMESPACE::OFF
#define STEREO_VR_EXCLUSIVITY_FLAGS_APP_PROFILE_ENUM  EN_NONE
namespace STEREO_VR_EXCLUSIVITY_FLAGS_NAMESPACE
{
    enum STEREO_VR_EXCLUSIVITY_FLAGS_ENUM 
    {
        OFF = 0x00000000,
        DESKTOP_ONLY_APP = 0x00000000,
        _0 = 0x00000000,
        VR_ONLY_APP = 0x00000001,
        _1 = 0x00000001,
        DESKTOP_VR_DUAL_MODE_APP = 0x00000002,
        _2 = 0x00000002,
        VR_RUNTIME_COMPONENT = 0x00000004,
        _4 = 0x00000004,
        DESKTOP_STEREO_APP_WITH_ADDED_VR_SUPPORT = 0x00000008,
        _8 = 0x00000008
    };
}


#define STEREO_VSH0_PREFIX            "_"
#define STEREO_VSH0_STRING            ""
#define STEREO_VSH0_ID                0x708b7af8
#define STEREO_VSH0_STRING_PLAIN      "STEREO_VSH0"
#define STEREO_VSH0_OVERINSTALL       0 // OVERRIDE
#define STEREO_VSH0_APP_PROFILE_ENUM  EN_NONE


#define STEREO_VSH1_PREFIX            "_"
#define STEREO_VSH1_STRING            ""
#define STEREO_VSH1_ID                0x708b7af9
#define STEREO_VSH1_STRING_PLAIN      "STEREO_VSH1"
#define STEREO_VSH1_OVERINSTALL       0 // OVERRIDE
#define STEREO_VSH1_APP_PROFILE_ENUM  EN_NONE


#define STEREO_VSH10_PREFIX            "_"
#define STEREO_VSH10_STRING            ""
#define STEREO_VSH10_ID                0x708b7b02
#define STEREO_VSH10_STRING_PLAIN      "STEREO_VSH10"
#define STEREO_VSH10_OVERINSTALL       0 // OVERRIDE
#define STEREO_VSH10_APP_PROFILE_ENUM  EN_NONE


#define STEREO_VSH2_PREFIX            "_"
#define STEREO_VSH2_STRING            ""
#define STEREO_VSH2_ID                0x708b7afa
#define STEREO_VSH2_STRING_PLAIN      "STEREO_VSH2"
#define STEREO_VSH2_OVERINSTALL       0 // OVERRIDE
#define STEREO_VSH2_APP_PROFILE_ENUM  EN_NONE


#define STEREO_VSH3_PREFIX            "_"
#define STEREO_VSH3_STRING            ""
#define STEREO_VSH3_ID                0x708b7afb
#define STEREO_VSH3_STRING_PLAIN      "STEREO_VSH3"
#define STEREO_VSH3_OVERINSTALL       0 // OVERRIDE
#define STEREO_VSH3_APP_PROFILE_ENUM  EN_NONE


#define STEREO_VSH4_PREFIX            "_"
#define STEREO_VSH4_STRING            ""
#define STEREO_VSH4_ID                0x708b7afc
#define STEREO_VSH4_STRING_PLAIN      "STEREO_VSH4"
#define STEREO_VSH4_OVERINSTALL       0 // OVERRIDE
#define STEREO_VSH4_APP_PROFILE_ENUM  EN_NONE


#define STEREO_VSH5_PREFIX            "_"
#define STEREO_VSH5_STRING            ""
#define STEREO_VSH5_ID                0x708b7afd
#define STEREO_VSH5_STRING_PLAIN      "STEREO_VSH5"
#define STEREO_VSH5_OVERINSTALL       0 // OVERRIDE
#define STEREO_VSH5_APP_PROFILE_ENUM  EN_NONE


#define STEREO_VSH6_PREFIX            "_"
#define STEREO_VSH6_STRING            ""
#define STEREO_VSH6_ID                0x708b7afe
#define STEREO_VSH6_STRING_PLAIN      "STEREO_VSH6"
#define STEREO_VSH6_OVERINSTALL       0 // OVERRIDE
#define STEREO_VSH6_APP_PROFILE_ENUM  EN_NONE


#define STEREO_VSH7_PREFIX            "_"
#define STEREO_VSH7_STRING            ""
#define STEREO_VSH7_ID                0x708b7aff
#define STEREO_VSH7_STRING_PLAIN      "STEREO_VSH7"
#define STEREO_VSH7_OVERINSTALL       0 // OVERRIDE
#define STEREO_VSH7_APP_PROFILE_ENUM  EN_NONE


#define STEREO_VSH8_PREFIX            "_"
#define STEREO_VSH8_STRING            ""
#define STEREO_VSH8_ID                0x708b7b00
#define STEREO_VSH8_STRING_PLAIN      "STEREO_VSH8"
#define STEREO_VSH8_OVERINSTALL       0 // OVERRIDE
#define STEREO_VSH8_APP_PROFILE_ENUM  EN_NONE


#define STEREO_VSH9_PREFIX            "_"
#define STEREO_VSH9_STRING            ""
#define STEREO_VSH9_ID                0x708b7b01
#define STEREO_VSH9_STRING_PLAIN      "STEREO_VSH9"
#define STEREO_VSH9_OVERINSTALL       0 // OVERRIDE
#define STEREO_VSH9_APP_PROFILE_ENUM  EN_NONE


#define STEREO_WATCHDOG_PREFIX            "_"
#define STEREO_WATCHDOG_STRING            ""
#define STEREO_WATCHDOG_ID                0x700a5654
#define STEREO_WATCHDOG_STRING_PLAIN      "STEREO_WATCHDOG"
#define STEREO_WATCHDOG_OVERINSTALL       0 // OVERRIDE
#define STEREO_WATCHDOG_APP_PROFILE_ENUM  EN_NONE


#define STEREO_WRITECONFIG_PREFIX            "_"
#define STEREO_WRITECONFIG_STRING            ""
#define STEREO_WRITECONFIG_ID                0x700498b3
#define STEREO_WRITECONFIG_STRING_PLAIN      "STEREO_WRITECONFIG"
#define STEREO_WRITECONFIG_OVERINSTALL       0 // OVERRIDE
#define STEREO_WRITECONFIG_APP_PROFILE_ENUM  EN_NONE


#define STEREO_ZDIRECTION_PREFIX            "_"
#define STEREO_ZDIRECTION_STRING            ""
#define STEREO_ZDIRECTION_ID                0x70b17872
#define STEREO_ZDIRECTION_STRING_PLAIN      "STEREO_ZDIRECTION"
#define STEREO_ZDIRECTION_OVERINSTALL       0 // OVERRIDE
#define STEREO_ZDIRECTION_APP_PROFILE_ENUM  EN_NONE


#define STEREO_ZINF_PREFIX            "_"
#define STEREO_ZINF_STRING            ""
#define STEREO_ZINF_ID                0x70fc13ad
#define STEREO_ZINF_STRING_PLAIN      "STEREO_ZINF"
#define STEREO_ZINF_OVERINSTALL       0 // OVERRIDE
#define STEREO_ZINF_APP_PROFILE_ENUM  EN_NONE


#define STEREO_ZSCR_PREFIX            "_"
#define STEREO_ZSCR_STRING            ""
#define STEREO_ZSCR_ID                0x707f0e69
#define STEREO_ZSCR_STRING_PLAIN      "STEREO_ZSCR"
#define STEREO_ZSCR_OVERINSTALL       0 // OVERRIDE
#define STEREO_ZSCR_APP_PROFILE_ENUM  EN_NONE


#define STEREO__VERSION_PREFIX            "_"
#define STEREO__VERSION_STRING            ""
#define STEREO__VERSION_ID                0x70ceb412
#define STEREO__VERSION_STRING_PLAIN      "STEREO__VERSION"
#define STEREO__VERSION_OVERINSTALL       0 // OVERRIDE
#define STEREO__VERSION_APP_PROFILE_ENUM  EN_NONE


